In [1]:
import pandas as pd
import requests
from io import StringIO

C:\Users\HP\AppData\Roaming\Python\Python313\site-packages\pandas\core\computation\expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

### Problem-1:

You are given a SQL file link: https://drive.google.com/file/d/1WFt7B84LTHhMueoKmz8W-PRo7xXqmZf3/view?usp=share_link. Read the data by using the file and store it in a excel file. In this data, there are 3 tables named "invoices", "order_leads" and "sales_sql". So create 3 sheets to your excel file.

In [1]:
# code here
import mysql.connector

con = mysql.connector.connect(host='localhost', password='', user='root', database='import_practice')

In [6]:
invoices = pd.read_sql_query('select * from invoices', con)
orderleads = pd.read_sql_query('select * from orderleads', con)
salesteam = pd.read_sql_query('select * from salesteam', con)

C:\Users\HP\AppData\Local\Temp\ipykernel_33296\2082939.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  invoices = pd.read_sql_query('select * from invoices', con)
C:\Users\HP\AppData\Local\Temp\ipykernel_33296\2082939.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  orderleads = pd.read_sql_query('select * from orderleads', con)
C:\Users\HP\AppData\Local\Temp\ipykernel_33296\2082939.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  salesteam = pd.read_sql_query('select * from salesteam', con)

In [7]:
with pd.ExcelWriter('data/27_data/output.xlsx') as writer:
    invoices.to_excel(writer, sheet_name='invoices')
    orderleads.to_excel(writer, sheet_name='orderleads')
    salesteam.to_excel(writer, sheet_name='salesteam')

### Problem-2

Go to the site: https://rapidapi.com/wirefreethought/api/geodb-cities. From here, you have to grab the API and have to choose proper routes to get the cities of different countries. After getting the right API, hit that API and create a dataframe of all the cities that you can get by using the API. Then store the dataframe to a SQL. If you need to create an account or have to subscribe, then do that (it has free subscription but has some limitations. Use that free subscription and modify your accordingly to get all the data).

In [ ]:
import requests

url = "https://wft-geo-db.p.rapidapi.com/v1/geo/cities"

headers = {
	"x-rapidapi-key": "f7d4abf8a7msh77c078b9c649e87p1440fdjsn7b708d21a0f4",
	"x-rapidapi-host": "wft-geo-db.p.rapidapi.com"
}

lis = []
ofset = 0
for i in range(1, 8980):
	params={
		"limit":10,
		"offset":ofset
	}
	ofset = params['limit']*i
	response = requests.get(url, headers=headers, params=params)
	for j in response.json()["data"]:
		lis.append(j)
	if i==744360:
		print(f'successfully added {i} records.')

In [51]:
df = pd.DataFrame(lis)

In [53]:
df.head()

,id,wikiDataId,type,city,name,country,countryCode,region,regionCode,regionWdId,latitude,longitude,population
0,3350606,Q24668,CITY,Aixirivall,Aixirivall,Andorra,AD,Sant Julià de Lòria,06,Q24282,42.462450,1.502090,1025
1,3216144,Q24656,CITY,Aixovall,Aixovall,Andorra,AD,Sant Julià de Lòria,06,Q24282,42.476358,1.489492,69
2,3406038,Q4699394,CITY,Aixàs,Aixàs,Andorra,AD,Sant Julià de Lòria,06,Q24282,42.486389,1.467222,0
3,397,Q1863,CITY,Andorra la Vella,Andorra la Vella,Andorra,AD,Andorra la Vella,07,Q2522163,42.507222,1.522222,24042
4,3360277,Q24475,CITY,Ansalonga,Ansalonga,Andorra,AD,Ordino,05,Q24272,42.568443,1.521571,49

In [54]:
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:@localhost/country_detail")
df.to_sql('coutry', con=engine, if_exists='append')

8980

### Problem 3:

Go to this url: https://www.flipkart.com/search?q=smartphones. This is the url to find phones in flipkart website. You have to extract the below things:
1. image url of the phone
2. name of the image
3. average ratings
4. total ratings
5. total reviews
6. discounted price
7. actual price

Extract all the phones which are available in this website. So you have to use the pagination concept. **Also after requesting every page through the url, please wait for a while (minimum 2-3 seconds), otherwise your IP address can be banned to access the flipkart website later.**

After collecting all the data, save that in a JSON file.

In [88]:
# code here

import requests
from bs4 import BeautifulSoup
import numpy as np
import pandas as pd
import time

In [94]:
img_url = []
name = []
avg = []
total = []
rew = []
dis = []
act = []


for j in range(1, 5):
    time.sleep(3)
    url = f'https://www.flipkart.com/search?q=smartphones&page={j}'

    headers = {
    'User-Agent':
    'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
    response = requests.get(url, headers=headers)
    print(j, response.status_code)
    soup = BeautifulSoup(response.text, 'html.parser')
    box = soup.find_all('div', class_='nZIRY7')


    for i in box:
        try:
            img_url.append("flipkart.com" + i.find('a', class_='k7wcnx').get('href'))
        except Exception as e:
            print("img", e)
            img_url.append(np.nan)
            
        try:
            name.append(i.find('div', class_='RG5Slk').text)
        except Exception as e:
            print("name", e)
            name.append(np.nan)
            
        try:
            avg.append(i.find('div', class_='MKiFS6').text)
        except Exception as e:
            print("avg", e)
            avg.append(np.nan)
            
        try:
            total.append(i.find('span', class_='PvbNMB').find('span').find('span').text.replace('Ratings', "").strip())
        except Exception as e:
            print("total", e)
            total.append(np.nan)
        
        try:
            review = i.select_one(".PvbNMB > span > span:nth-child(3)")
            rew.append(review.get_text(strip=True).replace("Reviews", "").strip())
        except Exception as e:
            print("rew", e)
            rew.append(np.nan)
        
        try:
            dis.append(i.find('div', class_='hZ3P6w DeU9vF').text)
        except Exception as e:
            print('dis', e)
            dis.append(np.nan)
        
        try:
            act.append(i.find('div', class_='kRYCnD gxR4EY').text)
        except Exception as e:
            print("act", e)
            act.append(np.nan)

1 403
2 403
3 403
4 403

In [86]:
dic = {
    "img_url":img_url,
    "name":name,
    "avg_rating":avg,
    "total_rating":total,
    "review":rew,
    "discount_price":dis,
    "actual_prices":act
}

In [87]:
pd.DataFrame(dic)

,img_url,name,avg_rating,total_rating,review,discount_price,actual_prices
0,flipkart.com/vivo-x200t-stellar-black-256-gb/p...,"vivo X200T (Stellar Black, 256 GB)",4.6,"7,919","1,584","₹59,999","₹80,000"
1,flipkart.com/redmi-a7-black-64-gb/p/itmb3debae...,"REDMI A7 (Black, 64 GB)",4,133,7,"₹12,499","₹14,999"
2,flipkart.com/motorola-g37-power-pantone-capri-...,"MOTOROLA g37 power (PANTONE Capri, 64 GB)",4.2,"4,496",459,"₹14,999","₹26,499"
3,flipkart.com/ai-pulse-2-purple-64-gb/p/itmdc91...,"Ai+ Pulse 2 (Purple, 64 GB)",4.2,"8,249",519,"₹9,199","₹10,999"
4,flipkart.com/motorola-g37-power-pantone-impene...,"MOTOROLA g37 power (PANTONE Impenetrable, 128 GB)",4.2,"4,496",459,"₹15,999","₹30,499"
5,flipkart.com/motorola-g37-power-pantone-impene...,"MOTOROLA g37 power (PANTONE Impenetrable, 64 GB)",4.2,"4,496",459,"₹14,999","₹26,499"
6,flipkart.com/vivo-t5x-5g-cyber-green-128-gb/p/...,"vivo T5x 5G (Cyber Green, 128 GB)",4.4,"17,064","1,134","₹24,999","₹28,999"
7,flipkart.com/motorola-g37-power-pantone-capri-...,"MOTOROLA g37 power (PANTONE Capri, 128 GB)",4.2,"4,496",459,"₹15,999","₹30,499"
8,flipkart.com/samsung-galaxy-f07-green-64-gb/p/...,"Samsung Galaxy F07 (Green, 64 GB)",4.3,"9,281",655,"₹11,499","₹11,999"
9,flipkart.com/ai-nova-2-5g-purple-128-gb/p/itmc...,"Ai+ Nova 2 5G (Purple, 128 GB)",4.3,"4,984",234,"₹13,999","₹17,499"
10,flipkart.com/motorola-g37-power-pantone-impene...,"MOTOROLA g37 power (PANTONE Impenetrable, 128 GB)",4.1,"1,108",98,"₹19,999","₹37,999"
11,flipkart.com/vivo-t5-lite-44w-5g-wave-blue-128...,"vivo T5 Lite 44W 5G (Wave Blue, 128 GB)",4.3,"1,073",83,"₹21,999","₹38,499"
12,flipkart.com/realme-p4-lite-beach-gold-64-gb/p...,"realme P4 Lite (Beach Gold, 64 GB)",4,"5,277",328,"₹12,999","₹24,999"
13,flipkart.com/realme-c100x-golden-coast-64-gb/p...,"realme C100x (Golden Coast, 64 GB)",4,86,13,"₹14,999","₹29,999"
14,flipkart.com/ai-nova-2-5g-blue-64-gb/p/itm20a7...,"Ai+ Nova 2 5G (Blue, 64 GB)",4.3,"4,984",234,"₹12,999","₹13,999"
15,flipkart.com/hmd-vibe2-5g-peach-pink-128-gb/p/...,"HMD Vibe2 5G (Peach Pink, 128 GB)",4.5,"4,164",395,"₹16,999","₹19,999"
16,flipkart.com/ai-nova-2-pro-5g-purple-128-gb/p/...,"Ai+ Nova 2 Pro 5G (Purple, 128 GB)",4.1,"1,004",121,"₹15,999","₹21,999"
17,flipkart.com/motorola-g06-power-pantone-tapest...,"MOTOROLA g06 power (Pantone tapestry, 64 GB)",4.2,"22,209","1,527","₹13,999","₹19,999"
18,flipkart.com/ai-pulse-2-pink-64-gb/p/itmb3d9ab...,"Ai+ Pulse 2 (Pink, 64 GB)",4.2,"8,249",519,"₹9,199","₹10,999"
19,flipkart.com/ai-pulse-2-blue-64-gb/p/itm916850...,"Ai+ Pulse 2 (Blue, 64 GB)",4.2,"8,249",519,"₹9,199","₹10,999"
20,flipkart.com/motorola-g67-power-5g-pantone-cil...,"MOTOROLA g67 power 5G (Pantone CILANTRO, 256 GB)",4.2,777,62,"₹26,999","₹30,999"
21,flipkart.com/motorola-g06-power-pantone-tendri...,"MOTOROLA g06 power (Pantone Tendril, 64 GB)",4.2,"22,209","1,527","₹13,999","₹19,999"
22,flipkart.com/oneplus-nord-ce6-lite-hyper-black...,"OnePlus Nord CE6 Lite (Hyper Black, 128 GB)",4.3,576,35,"₹27,160","₹33,999"
23,flipkart.com/realme-p4r-5g-silver-glare-128-gb...,"realme P4R 5G (Silver Glare, 128 GB)",4.2,"1,674",143,"₹19,499","₹34,999"