**Problem:**

You are given the following dataset:
1. **Audible Data** : https://1drv.ms/u/s!AiqdXCxPTydhoog8ckLN-6Cw55fzIg?e=EWgZ5d

Your task is to:
- Find the problems with the datasets.
- Define the Data Quality Dimensions.
- Try to clean the datasets.

In [247]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [248]:
df = pd.read_csv('data/28_data/audible_uncleaned.csv', encoding='UTF-8')

In [249]:
df.sample(5)

,name,author,narrator,time,releasedate,language,stars,price
4429,How I Do My Homework,Writtenby:JenniferBoothroyd,Narratedby:Intuitive,1 min,22-01-20,English,Not rated yet,164.00
40215,Russia,Writtenby:GregoryCarleton,Narratedby:JamesCameronStewart,10 hrs and 35 mins,14-06-17,English,Not rated yet,836.00
64966,"Oh, my God!",Writtenby:DamiánMollá,Narratedby:DamiánMollá,6 hrs and 19 mins,23-09-21,spanish,Not rated yet,729.00
77031,Cocky Outlaw,"Writtenby:CrystalDaniels,SandyAlvarez,HeroClub","Narratedby:ThomasOakley,SierraGrace",2 hrs and 56 mins,21-06-21,English,Not rated yet,233.00
69924,It's Not My Fault,"Writtenby:HenryCloud,JohnTownsend","Narratedby:HenryCloud,JohnTownsend",6 hrs and 18 mins,10-07-09,English,5 out of 5 stars2 ratings,539.00

<br>

# **Dataset Summary**

This dataset contains collection of audiobooks in different languages which is written by different authors and narrated by different narrator

# **Columns Description**

- `name` contain the name of the book.

- `author` contain the author name.

- `narrator` contain the narrators to make a recording of book in a story form.

- `time` contain the duration of the recorded audiobook.

- `releasedate` contain the date of release of book.

- `language` contain the book language.

- `stars` contain the rating of book.

- `price` contain the price of book.

# **Issues with Dataset**

### **Dirty data**

- `name` column has encoding problem and sometimes contain majibok  `validity`

- `releasedate` column contain inconsistence date and should convert to datetime datatype. `consistency`

- `price`column datatype should be int instead of str `validity`

### **Messy data**

- `author` column should only contain name of author instead text writtenby 

- `narrator` column should only contain names of narrator instead text narratedby

- `time` column should expand to make new columns of duration_min and duration_hour. Note time columns sometimes contain only hour, hour and min, and only min, and sometimes text as less than one mint.

- `stars` column should split into two columns stars and ratings

In [250]:
df.head()

,name,author,narrator,time,releasedate,language,stars,price
0,Geronimo Stilton #11 & #12,Writtenby:GeronimoStilton,Narratedby:BillLobely,2 hrs and 20 mins,04-08-08,English,5 out of 5 stars34 ratings,468.00
1,The Burning Maze,Writtenby:RickRiordan,Narratedby:RobbieDaymond,13 hrs and 8 mins,01-05-18,English,4.5 out of 5 stars41 ratings,820.00
2,The Deep End,Writtenby:JeffKinney,Narratedby:DanRussell,2 hrs and 3 mins,06-11-20,English,4.5 out of 5 stars38 ratings,410.00
3,Daughter of the Deep,Writtenby:RickRiordan,Narratedby:SoneelaNankani,11 hrs and 16 mins,05-10-21,English,4.5 out of 5 stars12 ratings,615.00
4,"The Lightning Thief: Percy Jackson, Book 1",Writtenby:RickRiordan,Narratedby:JesseBernstein,10 hrs,13-01-10,English,4.5 out of 5 stars181 ratings,820.00

In [251]:
df.sample(3)

,name,author,narrator,time,releasedate,language,stars,price
80681,Tales from the St. Louis Cardinals Dugout,"Writtenby:BobForsh,TomWheatley",Narratedby:MichaelScherer,3 hrs and 54 mins,02-04-13,English,Not rated yet,501.00
35921,Finding Freedom in Illness,Writtenby:PeterFernando,Narratedby:RogerClark,9 hrs and 8 mins,19-04-16,English,Not rated yet,668.00
84086,Who Done It?,Writtenby:JonScieszka,Narratedby:RebeccaGibel,7 hrs and 3 mins,13-12-18,English,Not rated yet,398.00

In [252]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 87489 entries, 0 to 87488
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         87489 non-null  str
 1   author       87489 non-null  str
 2   narrator     87489 non-null  str
 3   time         87489 non-null  str
 4   releasedate  87489 non-null  str
 5   language     87489 non-null  str
 6   stars        87489 non-null  str
 7   price        87489 non-null  str
dtypes: str(8)
memory usage: 16.1 MB

In [253]:
df.isna().sum().sum()

np.int64(0)

In [254]:
df.duplicated().sum()

np.int64(0)

In [255]:
df[df.duplicated(subset=['name'])]

,name,author,narrator,time,releasedate,language,stars,price
18,Merlin Mission Collection,Writtenby:MaryPopeOsborne,Narratedby:MaryPopeOsborne,10 hrs and 18 mins,02-05-17,English,5 out of 5 stars11 ratings,"1,256.00"
46,"The Lightning Thief: Percy Jackson, Book 1",Writtenby:RickRiordan,Narratedby:WalterLewis,3 hrs and 51 mins,13-01-10,English,4 out of 5 stars4 ratings,615.00
54,Merlin Mission Collection,Writtenby:MaryPopeOsborne,Narratedby:MaryPopeOsborne,13 hrs and 24 mins,02-05-17,English,5 out of 5 stars8 ratings,"1,256.00"
155,Barbie - Superprincesa,Writtenby:Mattel,Narratedby:VanessaPérezJurado,29 mins,07-03-22,spanish,Not rated yet,38.00
273,Barbie - Dreamtopia,"Writtenby:Mattel,MartaCisaMuñoz-traductor",Narratedby:MiriamMonlleo,21 mins,31-01-22,catalan,Not rated yet,38.00
...,...,...,...,...,...,...,...,...
87443,Travels with a Donkey in the Cevennes,Writtenby:RobertLouisStevenson,Narratedby:DenisLawson,2 hrs and 51 mins,13-05-08,English,Not rated yet,569.00
87456,Gettysburg,Writtenby:JeffShaara,Narratedby:RobertsonDean,1 hr and 12 mins,26-03-07,English,Not rated yet,200.00
87457,Solo,Writtenby:PenHadow,Narratedby:PenHadow,3 hrs and 5 mins,14-02-05,English,Not rated yet,615.00
87475,Wanderlust,Writtenby:ElisabethEaves,Narratedby:ErinBennett,9 hrs and 51 mins,26-02-14,English,Not rated yet,668.00
87486,The Innocents Abroad,Writtenby:MarkTwain,Narratedby:FloGibson,19 hrs and 4 mins,30-12-16,English,Not rated yet,938.00

<br>

# **Cleaning Dataset**

We have to clean the dataset in this order

1. **completeness**

2. **messy data**

3. **validity**

4. **accuracy**

5. **consistency**

# **Define solution**

- we have to remove the writtenby text from author column

- we have to remove the narratedby text from the narrator column

- we have to make columns duration_hour and duration_min

- we have to split the stars columns and make stars and rating columns

- we have to change the encoding of name column

- we have to change the datatype of price to float

- we have to change the datatype of releasedate to datetime

In [256]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 87489 entries, 0 to 87488
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         87489 non-null  str
 1   author       87489 non-null  str
 2   narrator     87489 non-null  str
 3   time         87489 non-null  str
 4   releasedate  87489 non-null  str
 5   language     87489 non-null  str
 6   stars        87489 non-null  str
 7   price        87489 non-null  str
dtypes: str(8)
memory usage: 16.1 MB

In [258]:
# code
df["author"] = df['author'].str.split(':').str.get(1).str.strip()

In [259]:
# test
df['author']

0        GeronimoStilton
1            RickRiordan
2             JeffKinney
3            RickRiordan
4            RickRiordan
              ...
87484       ChrisStewart
87485      StephenO'Shea
87486          MarkTwain
87487     LaurenceSterne
87488      MarkKurlansky
Name: author, Length: 87489, dtype: object

<br>

In [260]:
# code
df["narrator"] = df["narrator"].str.split(":").str.get(1).str.strip()

In [261]:
# test
df["narrator"]

0            BillLobely
1         RobbieDaymond
2            DanRussell
3        SoneelaNankani
4        JesseBernstein
              ...
87484      ChrisStewart
87485        RobertFass
87486         FloGibson
87487       AntonLesser
87488       FleetCooper
Name: narrator, Length: 87489, dtype: object

In [262]:
# code
def hr(text):
    t = text.split('and')
    if len(t)==2:
        hr = t[0].strip().split(' ')[0]
        min = t[1].strip().split(' ')[0]
        return (int(hr)*60)+int(min)
    elif (len(t)==1) & ("Less" in t[0]):
        return int(1)
    elif (len(t)==1) & ("mins" in t[0]):
        min = t[0].strip().split(' ')[0]
        return int(min)
    elif (len(t)==1) & ("hrs" in t[0]):
        hr = t[0].strip().split(' ')[0]
        return int(hr)*60
    else:
        return 'error'

In [263]:
df['duration_min'] = df['time'].apply(hr)

In [264]:
# test
df.sample(6)

,name,author,narrator,time,releasedate,language,stars,price,duration_min
28490,Mastering the Virtual Sale,KerryJohnsonMBAPhD,JaredZak,7 hrs and 1 min,25-01-22,English,Not rated yet,586.00,421
21974,Shadow Warriors of World War II,"GordonThomas,GregLewis",KateReading,11 hrs and 33 mins,01-01-17,English,Not rated yet,836.00,693
70158,Sandokan - Los Tigres de mompracén [The Tigers...,EmilioSalgari,JoanMora,4 hrs and 44 mins,05-03-20,spanish,Not rated yet,192.00,284
82744,Il re delle cicatrici,LeighBardugo,GiadaBonanomi,16 hrs and 31 mins,30-03-22,italian,Not rated yet,382.00,991
73671,Ladyen og landevejsrøveren,"BarbaraCartland,IngerVedersø",Anne-MetteJohansen,9 hrs and 4 mins,11-11-21,danish,Not rated yet,300.00,544
32917,Mayo Clinic Guide to Integrative Medicine,BrentA.Bauer,JonathanToddRoss,12 hrs and 12 mins,22-02-22,English,Not rated yet,938.00,732

In [322]:
# code
def starss(text):
    t = text.split('out')
    return t[0].strip()

df["star"] = df['stars'].apply(starss)


def rat(text):
    t = text.split('stars')
    if t[0]=="Not rated yet":
        return "Not rated yet"
    elif len(t)==2:
        r = t[1].strip().split(' ')[0]
        return r
    else:
        return 'error'
    
df["rating"] = df["stars"].apply(rat)

In [333]:
# test
df.sample(5)

,name,author,narrator,time,releasedate,language,stars,price,duration_min,star,rating
2563,My Life as a Stuntboy,JanetTashjian,TrevorGoble,2 hrs and 47 mins,17-03-20,English,Not rated yet,74.00,167,Not rated yet,Not rated yet
11109,The New Social Learning,"TonyBingham,MarciaConner",JamesBabson,6 hrs and 34 mins,10-12-10,English,Not rated yet,668.00,394,Not rated yet,Not rated yet
76830,Alt på spil,HeléneHolmström,PernilleLyneborg,9 hrs and 49 mins,04-03-22,danish,Not rated yet,703.00,589,Not rated yet,Not rated yet
14969,Documentary Superstars,MarshaMcCreadie,MelbaSibrel,9 hrs and 22 mins,13-02-13,English,Not rated yet,668.00,562,Not rated yet,Not rated yet
33134,The ABC of Better Sleep,MaxKirsten,MaxKirsten,2 hrs and 42 mins,09-07-10,English,Not rated yet,266.00,162,Not rated yet,Not rated yet

In [265]:
# code
def enc(text):
    try:
        return text.encode('latin1').decode('uft-8')
    except:
        return text
    
df["name"] = df['name'].apply(enc)

In [277]:
# test
df.sample(5)

,name,author,narrator,time,releasedate,language,stars,price,duration_min
76385,Aspettavo solo te,JessicaClare,VeronicaD'Arconte,8 hrs and 13 mins,10-10-20,italian,Not rated yet,574.00,493
41382,The Second Book of General Ignorance,"JohnLloyd,JohnMitchinson",JulianElfer,10 hrs and 46 mins,30-04-19,English,Not rated yet,703.00,646
38258,The Neanderthals Rediscovered,"DimitraPapagianni,MichaelA.Morse",NigelPatterson,5 hrs and 43 mins,31-10-17,English,4 out of 5 stars1 rating,668.00,343
38337,The Hesiod Collection,Hesiod,AndreaGiordani,2 hrs and 57 mins,07-05-19,English,Not rated yet,820.00,177
3916,Funny Songs and Silly Rhymes (German edition),"BeateBaylie,KarinSchweizer","BeateBaylie,KarinSchweizer",20 mins,23-06-20,german,Not rated yet,166.00,20

<br>

In [303]:
df["price"].unique()[df["price"].unique().isin(['Free'])]

<ArrowStringArray>
['Free']
Length: 1, dtype: str

In [342]:
# code

df["price"] = (df['price'].str.replace("Free", "0").str.replace(",", "")).astype('float').astype('int')

In [344]:
# test
df['price'].sample(4)

86707    234
63478    668
2202      99
60020    490
Name: price, dtype: int64

In [ ]:
# code

df["releasedate"] = pd.to_datetime(df["releasedate"])

C:\Users\HP\AppData\Local\Temp\ipykernel_20980\828161075.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["releasedate"] = pd.to_datetime(df["releasedate"])

In [360]:
# test
df.sample()

,name,author,narrator,time,releasedate,language,stars,price,duration_min,star,rating
3479,A Boy of Heart Mountain,BarbaraBazaldua,OvaSaopeng,3 hrs and 55 mins,2015-07-08,English,Not rated yet,435,235,Not rated yet,Not rated yet

<br>

---