<b><h1><center>Groupby Object</center></h1></b>

# **Groupby**
A GroupBy Object is a special Pandas object created by the groupby() method.

It does not immediately perform any calculations.

Instead, it:

- Splits the data into groups.
- Stores information about those groups.
- Waits for you to tell it what operation to perform.

Think of it as a manager that organizes your data but doesn't calculate anything until you ask.

# **The Big Idea**

**groupby() follows a famous three-step process:**

```
Split
   ↓
Apply
   ↓
Combine
```

This is known as the Split–Apply–Combine strategy.

- **Split:** Divide data into groups.
- **Apply:** Perform a function on each group.
- **Combine:** Merge the results into a single object.
  
**There should be always one categorical column for grouping and one or more numerical columns for applying any operation**

In [1]:
# import libraries
import numpy as np
import pandas as pd

C:\Users\HP\AppData\Roaming\Python\Python313\site-packages\pandas\core\computation\expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [2]:
# load the datasets
ipl = pd.read_csv('data/19_data/deliveries.csv')
movies = pd.read_csv('data/19_data/imdb-top-1000.csv')

In [3]:
# making dataframe to explain the groupby object

df = pd.DataFrame({
    "Name": ["Ali", "Sara", "Ahmed", "Bilal", "Hassan", "Ayesha"],
    "Department": ["IT", "HR", "IT", "HR", "Sales", "IT"],
    "Salary": [50000, 60000, 70000, 65000, 45000, 55000]
})

In [4]:
# it actually give a groupby object

grouped = df.groupby("Department")
print(grouped)        # it is a dataframegroupby object
type(grouped)

<pandas.api.typing.DataFrameGroupBy object at 0x000001F81B16FB60>

pandas.api.typing.DataFrameGroupBy

In [5]:
# we can perform any operation on groupby object

grouped.sum()

                      Name  Salary
Department
HR               SaraBilal  125000
IT          AliAhmedAyesha  175000
Sales               Hassan   45000

In [6]:
# we can select any column after applying any operation
grouped.sum()["Salary"]

Department
HR       125000
IT       175000
Sales     45000
Name: Salary, dtype: int64

In [7]:
# we can also do the same process in this way
grouped["Salary"].sum()          # this method is much faster than the above because the above method first apply operation on all columns
                                # and then we select columns while this process first select column then perform operation on selected column

Department
HR       125000
IT       175000
Sales     45000
Name: Salary, dtype: int64

In [8]:
# we can apply any math funtion as
grouped["Salary"].min()

Department
HR       60000
IT       50000
Sales    45000
Name: Salary, dtype: int64

In [9]:
grouped["Salary"].max()

Department
HR       65000
IT       70000
Sales    45000
Name: Salary, dtype: int64

In [10]:
grouped["Salary"].std()

Department
HR        3535.533906
IT       10408.329997
Sales             NaN
Name: Salary, dtype: float64

<br>

# **Groupby Attribute**

### **groups**
groups returns a dictionary where:

- Key = Group name
- Value = Index labels belonging to that group not the actual index position of row.

In [11]:
grouped.groups

{'HR': [1, 3], 'IT': [0, 2, 5], 'Sales': [4]}

In [12]:
ipl.set_index('batting_team').groupby('batsman').groups  # as it will return the dic with values of labels

{'A Ashish Reddy': ['Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', ...], 'A Chandila': ['Rajasthan Royals', 'Rajasthan Royals', 'Rajasthan Royals', 'Rajasthan Royals', 'Rajasthan Royals', 'Rajasthan Royals', 'Rajasthan Royals'], 'A Chopra': ['Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders', 'Kolkata Knight Riders'], 'A Choudhary': ['Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore'], 'A Dananjaya': ['Mumbai Indians', 'Mumbai Indians', 'Mumbai Indians', 'Mumbai Indians', 'Mumbai Indians'], 'A Flintoff': ['Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings'], 'A Hales': ['Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', 'Sunrisers Hyderabad', ...], 'A Joseph': ['Mumbai Indians', 'Mumbai Indians', 'Mumbai Indians', 'Mumbai Indians', 'Mumbai Indians', 'Mumbai Indians', 'Mumbai Indians', 'Mumbai Indians', 'Mumbai Indians', 'Mumbai Indians', 'Mumbai Indians', 'Mumbai Indians', 'Mumbai Indians'], 'A Kumble': ['Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore'], 'A Mishra': ['Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', ...], 'A Mithun': ['Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore'], 'A Mukund': ['Chennai Super Kings', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore', 'Royal Challengers Bangalore'], 'A Nehra': ['Mumbai Indians', 'Mumbai Indians', 'Mumbai Indians', 'Mumbai Indians', 'Mumbai Indians', 'Mumbai Indians', 'Mumbai Indians', 'Mumbai Indians', 'Mumbai Indians', 'Mumbai Indians', 'Mumbai Indians', 'Mumbai Indians', 'Mumbai Indians', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Pune Warriors', 'Pune Warriors', 'Pune Warriors', 'Pune Warriors', 'Pune Warriors', 'Pune Warriors', 'Pune Warriors', 'Pune Warriors', 'Pune Warriors', 'Pune Warriors', 'Pune Warriors', 'Pune Warriors', 'Pune Warriors', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Delhi Daredevils', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Chennai Super Kings', 'Sunrisers Hyderabad'], 'A Singh': ['Rajasthan Royals', 'Rajasthan Royals', 'Rajasthan Royals', 'Rajasthan Royals', 'Rajasthan Royals', 'Rajasthan Royals', 'Rajasthan Royals', 'Rajasthan Royals', 'Rajasthan Royals', 'Rajasthan Royals'], 'A Symonds': ['Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', ...], 'A Turner': ['Rajasthan Royals', 'Rajasthan Royals', 'Rajasthan Royals', 'Rajasthan Royals', 'Rajasthan Royals', 'Rajasthan Royals', 'Rajasthan Royals', 'Rajasthan Royals', 'Rajasthan Royals', 'Rajasthan Royals', 'Rajasthan Royals'], 'A Uniyal': ['Rajasthan Royals', 'Rajasthan Royals', 'Rajasthan Royals', 'Rajasthan Royals', 'Rajasthan Royals', 'Rajasthan Royals', 'Rajasthan Royals'], 'A Zampa': ['Rising Pune Supergiant', 'Rising Pune Supergiant', 'Rising Pune Supergiant', 'Rising Pune Supergiant', 'Rising Pune Supergiant', 'Rising Pune Supergiant', 'Rising Pune Supergiant', 'Rising Pune Supergiants'], 'AA Bilakhia': ['Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers', 'Deccan Chargers'], 'AA Chavan': ['Rajasthan Royals', 'Rajasthan Royals', 'Rajasthan Royals', 'Rajasthan Royals', 'Rajasthan Royals', 'Rajasthan Royals', 'Rajasthan Royals', 'Rajasthan Royals', 'Rajasthan Royals', 'Rajasthan Royals', 'Rajasthan Royals'], 'AA Jhunjhunwala': ['Rajasthan Royals', 'Rajasthan Royals', 'Rajasthan Royals', 'Rajasthan Royals', 'Rajasthan Royals', 'R

### **indices**
indices returns a dictionary where

```
Key

↓

Group name

Value

↓

Integer positions of rows. not label
```

In [13]:
grouped.indices

{'HR': array([1, 3]), 'IT': array([0, 2, 5]), 'Sales': array([4])}

In [14]:
ipl.set_index('batting_team').groupby('batsman').indices # it will instead return the index position

{'A Ashish Reddy': array([ 81613,  81614,  81615,  81616,  81618,  81622,  81623,  81624,
         81625,  81626,  83206,  83211,  83212,  84897,  84899,  84900,
         84902,  84903,  84904,  84906,  84907,  88280,  88281,  88282,
         88283,  88883,  88884,  88885,  88887,  88889,  90831,  90838,
         90840,  90841,  91881,  91883,  91884,  91885,  91887,  91889,
         91890,  91892,  91894,  91895,  91897,  91898,  93322,  93324,
         93325,  93326,  93327,  93329,  93330,  93331,  93332,  94073,
         94076,  94077,  94079,  94080,  95178,  95182,  95184,  95185,
         95187,  95188,  95190,  95191,  95192,  95194,  95197,  95198,
         95200,  95201,  95204,  96018,  96022,  96024,  96026,  96027,
         96028,  96032,  98057,  98058,  98059,  98062,  98063,  98064,
         98065,  98068,  98071,  98072,  98077,  98078,  98079,  98080,
         98081,  98082,  98534,  98535,  98540,  98543,  98544,  98545,
         98546,  98548,  98549,  98550,  98553, 101502, 101503, 101505,
        101506, 101507, 101508, 101510, 102378, 102382, 102385, 102387,
        125520, 125521, 125526, 125529, 125534, 125535, 125536, 125538,
        125540, 126127, 126129, 126131, 126137, 126138, 126139, 126140,
        126142, 129070, 129071, 129072, 129076, 129078, 129083, 129084,
        129085, 130532, 130533, 130534, 130536, 130537, 130538, 135246,
        135247, 135248, 135249, 135252, 135254, 135255, 135256, 135258,
        135259, 135261, 135262, 135263, 135265, 135266, 137213, 137216,
        137217, 137219, 137220, 137221, 137222, 137223, 137224, 137225,
        137226, 137227, 137229, 137231, 137232, 137233, 137234, 137239,
        138061, 138063, 138065, 138067, 138068, 138069, 138071, 138073,
        138074, 142600, 142601, 142603]),
 'A Chandila': array([88164, 96372, 96374, 96375, 96385, 96386, 96387]),
 'A Chopra': array([20477, 20478, 20482, 20484, 20490, 21373, 21374, 21375, 21376,
        21380, 21381, 21390, 21401, 21402, 21403, 21409, 21413, 21414,
        21415, 21416, 21418, 21419, 21420, 21421, 21422, 21424, 21425,
        21426, 21427, 21429, 22086, 22087, 22088, 22094, 22095, 22096,
        22100, 22104, 22105, 22106, 22107, 22108, 22110, 22113, 22114,
        22115, 22122, 22123, 23040, 23041, 23049, 23050, 26131, 26132,
        26134, 27956, 27957, 27958, 27959, 27960, 27962, 27963, 27964,
        27967, 27968, 27969, 27976, 27979, 27980, 27981, 27982, 27983,
        27984, 27986, 27988]),
 'A Choudhary': array([ 246,  247, 7019, 7020, 7022, 7024, 7026, 7027, 7033, 7035, 7036,
        7037, 7038, 7040, 9941, 9943, 9944, 9946, 9948, 9949]),
 'A Dananjaya': array([152403, 152404, 152405, 152407, 152410]),
 'A Flintoff': array([27490, 27491, 27492, 27493, 27496, 27497, 27498, 27499, 27500,
        27501, 27502, 27503, 27504, 27508, 27509, 27514, 27517, 27518,
        27522, 27524, 27526, 27527, 27528, 27530, 27532, 28222, 28223,
        28225, 28226, 28228, 28229, 28230, 28232, 28234, 28238, 28240,
        28241, 28244, 28245, 28965, 28966, 28968, 28970, 28973, 28974,
        28975, 28978, 28979, 28985, 28988, 28990, 28991, 28992, 28993,
        28994, 28995, 28998]),
 'A Hales': array([156866, 156868, 156869, 156870, 156871, 156872, 156873, 156874,
        156875, 156880, 156887, 156888, 156890, 156894, 156896, 156897,
        156900, 156901, 156903, 156905, 156909, 156910, 156913, 156914,
        156916, 156917, 156918, 156920, 156921, 156922, 156923, 156924,
        156926, 156928, 156930, 156931, 156939, 156944, 156946, 158871,
        158872, 158873, 158877, 158878, 158879, 158880, 158884, 158887,
        158888, 158892, 158893, 158895, 158896, 158897, 158898, 158900,
        158902, 158905, 158906, 158907, 158908, 158910, 158912, 158913,
        158914, 158916, 158918, 158919, 158921, 158923, 158926, 159477,
        159479, 159480, 159489, 159492, 160325, 160326, 160327, 160328,
        160329, 160330, 160332, 160333, 160334, 160335, 161188, 161189,
        161190, 161191, 161192, 161198, 161201, 161205, 161207, 162417,
        162418, 162423, 162424, 162425, 162426, 162427, 162428, 162429,
        162431, 162432, 162434, 162436, 162439, 162441, 162442, 162447,
        162448, 162452, 162454, 162455, 162457, 162458, 162460]),
 'A Joseph': array([170557, 170558, 170561, 170562, 170565, 170567, 170568, 170569,
        170570, 170576, 170580, 170581, 170583]),
 'A Kumble': array([19659, 19660, 19661, 19662, 19663, 19666, 19667, 21987, 23519,
        23520, 23522, 23529, 23530, 23532, 23535, 23538, 24803, 28332,
        28333, 28334, 28338, 28339, 28776, 29409, 29410, 29411, 32345,
        32346, 32348, 32349, 35817, 35820, 35822, 35825, 35826, 35831,
        40951, 46545, 49464, 52142, 52143, 52146, 52147, 53558, 53559,
        53562, 54763, 54764, 54765]),
 'A Mishra': array([  1186,   1187,   1188,   1190,   1191,   1193,   1194,   1196,
          1197,   1199,   1200,   1201,   1205,   1207,   8193,   8194,
          8195,   8198,   8199,   8202,   8204,   8205,   8207,   8208,
          8209,  10374,  10375,  10378,  10379,  10380,  10383,  10384,
         10388,  10390,  10391,  10392,  10394,  10395,  10396,  10397,
         11594,  11595,  11955,  11956,  11959,  11960,  11962,  11963,
         11964,  11968,  11969,  11974,  12980,  12983,  12984,  12985,
         21707,  21712,  21713,  21714,  21716,  22260,  22263,  22265,
         22266,  22269,  22270,  22275,  22277,  22278,  22279,  22281,
         22283,  22285,  22287,  22289,  22290,  22291,  22293,  22296,
         22297,  22298,  22299,  22300,  22301,  22303,  22306,  22307,
         22309,  22312,  22315,  22316,  22318,  26862,  26863,  26864,
         26866,  26867,  30863,  30864,  30865,  30870,  32959,  32960,
         32964,  32965,  32966,  32967,  32968,  32969,  36905,  36907,
         36910,  39983,  39985,  39986,  39987,  40357,  43116,  43117,
         43132,  43134,  43135,  43474,  43475,  43477,  44559,  50434,
         50435,  50438,  50439,  50442,  50443,  51509,  51511,  51512,
         51514,  51515,  51517,  51525,  51528,  51531,  51533,  51534,
         51535,  52351,  52352,  52354,  52356,  52358,  52360,  52361,
         52363,  52364,  52365,  52367,  52369,  52371,  52373,  52375,
         52377,  52379,  54234,  54236,  54237,  54239,  54242,  54243,
         54245,  54246,  54247,  54248,  55817,  55819,  56835,  56841,
         56842,  56844,  56851,  56852,  58912,  61588,  61590,  61591,
         61596,  61597,  61598,  61600,  61601,  61602,  61605,  61606,
         61608,  61611,  61613,  61614,  61615,  61618,  61619,  61620,
         62696,  64486,  64487,  64489,  64490,  64491,  65193,  65194,
         65195,  65196,  65201,  65202,  65204,  65205,  65206,  65207,
         67670,  68986,  68987,  68989,  68993,  68994,  68995,  68996,
         74421,  74422,  76083,  76084,  76085,  76091,  76093,  76094,
         76095,  79454,  81629,  81630,  81632,  81633,  81634,  81636,
         84910,  84912,  84914,  84916,  84917,  93333,  93334,  93335,
         93336,  93337,  93338,  93339,  93340,  93341,  93343,  93345,
         93346,  93349,  93350,  94098,  95152,  95153,  95154,  95157,
         95160,  95161,  95163,  95164,  95170,  95174,  95179,  95180,
         95181,  95183,  95186,  95189,  95193,  95195,  95196,  95199,
         95202,  95203,  95205,  95206,  95207,  95208,  97991,  97993,
         97994,  97995,  97997,  97999,  98000,  98001,  98002,  98003,
         98005,  98007,  98008,  98010,  98011,  98013,  98014,  98015,
         98017,  98018,  98021,  98477,  98478,  98479,  98480,  98486,
         98487,  98488,  98489,  98491,  98492,  98493,  98494,  98495,
         98496,  98497,  98499,  98500,  98501,  98503,  98505,  98506,
         98507,  98508,  98509,  98515,  98516,  98517,  98520,  98525,
         98526,  98527,  98529,  98530, 103186, 103187, 103188, 103189,
        103190, 103191, 103196, 103197, 110548, 110549, 110552, 110556,
        110557, 115453, 115454, 123180, 123181, 123182, 123185, 123186,
        126996, 128872, 128874, 128878, 128879, 131171, 131173, 131174,
        136665, 136666, 136670, 136671, 136674, 136676, 136677, 136678,
        136679, 147404, 147408, 147409, 147412, 147413, 155644, 155646,
        172988, 172990, 172991, 172993, 172995, 172996, 172997, 173003,
        173004, 176664, 176665, 176667, 176670, 176671, 176673, 176680,
        176681, 176683, 176684, 176685, 178585, 178586, 178589, 178701,
        178706, 178707]),
 'A Mithun': array([ 49455,  49456,  49457,  49462,  62309,  62310,  66306,  66307,
         66309,  69988,  69989,  69993,  69999,  70000,  70001,  70002,
         72409,  72412,  72413,  72414,  72415,  72416,  72419,  72424,
        104552, 104553]),
 'A Mukund': array([25667, 99423, 99429, 99434, 99435, 99441, 99443, 99444, 99445,
        99446, 99449, 99452, 99454, 99455, 99458, 99459, 99461, 99462,
        99465, 99466, 99470, 99472, 99473]),
 'A Nehra': array([ 15737,  15738,  16221,  16222,  16225,  16231,  16233,  16234,
         16235,  16236,  16237,  16238,  24679,  37657,  51530,  51532,
         51536,  51537,  54249,  54250,  54251,  54254,  54255,  54256,
         54262,  54264,  54265,  54266,  54268,  54269,  54272,  54273,
         54276,  54278,  75608,  75609,  75611,  75615,  75618,  86335,
         86337,  86338,  86340,  86342,  86344,  86345,  86346,  90357,
         92393,  92394,  92399,  92400,  92401, 101473, 105861, 125032,
        125034, 125036, 125038, 127687, 131303, 135628, 146231]),
 'A Singh': array([38746, 39380, 39381, 59369, 59370, 67552, 67554, 75232, 75233,
        75234]),
 'A Symonds': array([14831, 14832, 14839, 14842, 14843, 14844, 14849, 14850, 14851,
        14859, 14861, 14862, 14864, 14865, 14866, 14867, 14868, 14870,
        14871, 14872, 14875, 14877, 14880, 14881, 14884, 14885, 14886,
        14891, 14893, 14896, 14897, 14898, 14899, 14900, 14901, 14902,
        14903, 14904, 14905, 14908, 14911, 15312, 15313, 15314, 15315,
        15316, 15318, 15319, 15320, 15321, 15322, 15324, 15332, 15337,
        15759, 15765, 15766, 15767, 15768, 15769, 15771, 15772, 15773,
        15774, 15775, 15776, 15777, 15778, 15779, 15782, 15783, 15784,
        15785, 15787, 15789, 15790, 15791, 15794, 15797, 15798, 15799,
        15803, 15806, 15807, 15808, 15811, 15814, 15816, 15817, 15818,
        15821, 15825, 15827, 15828, 15829, 15831, 15832, 15833, 15835,
        15836, 15839, 15840, 15846, 15847, 15849, 15850, 15854, 15855,
        15856, 15857, 15859, 35155, 35156, 35157, 35158, 35162, 35163,
        35164, 35165, 35166, 35168, 35169, 35174, 35178, 35181, 35182,
        35184, 35185, 35187, 35188, 35189, 35190, 35193, 35194, 35195,
        35196, 35197, 35198, 35199, 35200, 35204, 35208, 35209, 35210,
        35212, 35215, 35216, 35217, 36105, 36107, 36108, 36109, 36112,
        36114, 36115, 36118, 36119, 36121, 36122, 36123, 36124, 36127,
        36128, 36132, 36133, 36136, 36137, 36985, 36986, 36988, 36989,
        36990, 36991, 36993, 36994, 36995, 36996, 37000, 37001, 37002,
        37003, 37004, 37005, 37006, 37007, 37008, 37019, 37020, 37021,
        37025, 38222, 38226, 38231, 38232, 38235, 38238, 38242, 38243,
        38244, 38245, 38246, 38247, 38249, 38423, 38424, 38425, 38430,
        38432, 38438, 38439, 38440, 38441, 38442, 38444, 38446, 38448,
        38449, 38450, 38457, 38458, 38462, 38463, 38464, 38465, 38466,
        38469, 38474, 38475, 38476, 40180, 40181, 40182, 40183, 40185,
        40186, 40187, 40188, 40189, 40190, 40191, 40195, 40196, 40198,
        40200, 40203, 40205, 40425, 40426, 40427, 40428, 40430, 40431,
        40432, 40435, 40436, 40437, 40442, 40443, 40444, 40445, 40446,
        40737, 40738, 40739, 40740, 40743, 40744, 40745, 40747, 40748,
        40750, 40751, 40752, 40755, 40756, 40757, 40758, 40759, 40761,
        40762, 40763, 40765, 41157, 41158, 41163, 41164, 41166, 41169,
        41170, 41171, 41173, 41986, 41988, 41989, 41990, 41991, 41992,
        41993, 41997, 41998, 42000, 42001, 42002, 42003, 42004, 42006,
        42022, 42025, 42026, 42027, 42028, 42029, 42030, 42031, 42033,
        42035, 42037, 42038, 42039, 42040, 42042, 42043, 42044, 42050,
        42051, 42052, 42054, 42056, 42057, 42058, 42059, 42060, 42064,
        42066, 42067, 42068, 42069, 43625, 43628, 43629, 43631, 43634,
        43635, 43636, 43640, 43642, 43645, 43648, 43649, 43650, 43654,
        43655, 43656, 43657, 43659, 43660, 43661, 43665, 43667, 43668,
        43669, 43670, 43675, 43676, 43680, 43681, 43682, 43684, 43690,
        43691, 43692, 43693, 43696, 43698, 43701, 44357, 44359, 44362,
        44363, 44365, 44367, 44368, 44369, 44370, 44373, 44378, 44381,
        44382, 44387, 44389, 44394, 44395, 44396, 44397, 44401, 44403,
        44404, 44405, 44407, 45845, 45846, 45847, 45848, 45849, 45850,
        45851, 45852, 45853, 45854, 45855, 45856, 45859, 45860, 45863,
        46950, 46951, 46953, 46954, 46955, 46956, 46957, 48186, 48187,
        48189, 48193, 48195, 48196, 48198, 48200, 48201, 48203, 48205,
        48206, 48208, 48210, 48211, 48212, 48213, 48214, 48215, 48216,
        48221, 48222, 48229, 48232, 48233, 48234, 48237, 48239, 48240,
        48241, 48243, 48244, 48245, 48246, 48247, 48248, 48249, 48251,
        48253, 48904, 48908, 48910, 48911, 48912, 48919, 48921, 48922,
        48924, 48927, 48928, 48929, 48930, 48934, 48937, 48938, 48940,
        48941, 48942, 49623, 49624, 49625, 49626, 49627, 49628, 49629,
        49632, 49633, 49635, 49636, 49637, 49639, 49641, 49649, 49650,
        49651, 49652, 49653, 49655, 50649, 50652, 50654, 50659, 50660,
        50661, 50662, 50663, 50664, 50668, 50669, 50670, 50674, 50675,
        50676, 50677, 50678, 50679, 50683, 50686, 50690, 50691, 50693,
        50694, 50695, 51127, 51132, 51133, 51136, 51137, 51140, 51142,
        51143, 51144, 51145, 51152, 51153, 51154, 51160, 51162, 51163,
        51164, 51166, 51168, 51170, 51173, 51174, 51175, 51178, 51179,
        51979, 51981, 51982, 51983, 51984, 51985, 51988, 51989, 51990,
        51991, 51992, 51994, 51996, 52000, 52002, 52003, 52004, 52006,
        52007, 52008, 52010, 53277, 53278, 53279, 53280, 53282, 53284,
        53285, 54075, 54076, 54077, 54078, 54079, 54080, 54081, 54083,
        54085, 54086, 54087, 54092, 54094, 54095, 54097, 54098, 54099,
        54101, 54102, 54103, 54104, 54105, 54107, 54109, 54110, 54111,
        54112, 54116, 54120, 54122, 54935, 54936, 54938, 54939, 54944,
        54945, 54948, 54949, 54950, 54951, 54959, 54960, 54961, 54967,
        54968, 54973, 54974, 54975, 54976, 54977, 54978, 54979, 54983,
        55029, 55030, 55031, 55032, 55040, 55041, 55044, 55046, 60104,
        60108, 60109, 60111, 60112, 60113, 60115, 60116, 60117, 60118,
        60122, 60126, 60129, 60131, 60132, 60700, 60701, 60702, 60703,
        60706, 60707, 60708, 60710, 60711, 60714, 60716, 60717, 60721,
        60722, 60723, 60724, 60727, 60728, 60732, 60733, 60734, 60739,
        60740, 60743, 60748, 60749, 60751, 60754, 60755, 61435, 61436,
        61438, 61439, 61440, 61441, 61443, 61446, 61449, 61450, 61456,
        61457, 61458, 61460, 61465, 61467, 61470, 61473, 61474, 61475,
        61476, 61479, 61481, 61482, 61484, 61485, 61486, 61487, 61488,
        61489, 61490, 61491, 61494, 63106, 63109, 63110, 63114, 63115,
        63116, 63117, 63120, 63121, 63122, 63125, 63128, 63129, 63130,
        63132, 63134, 63135, 63136, 63139, 63141, 63144, 63146, 63151,
        63153, 63154, 63156, 63158, 64601, 64602, 64604, 64606, 64609,
        64612, 65550, 65553, 65554, 66738, 66739, 66742, 66744, 67938,
        67944, 67955, 67956, 67957, 67958, 67959, 69031, 69032, 69034,
        69035, 69036, 69037, 69038, 69041, 69042, 69049, 69052, 69053,
        69054, 69056, 69062, 69063, 69064, 69065, 69068]),
 'A Turner': array([172508, 172509, 173491, 174311, 175652, 175654, 175655, 175656,
        175660, 175661, 175663]),
 'A Uniyal': array([41459, 42315, 42321, 42322, 42323, 42327, 42331]),
 'A Zampa': array([  2097,   2098,   2100,   2101,   2108,   2110,   2111, 145862]),
 'AA Bilakhia': array([30505, 30506, 30507, 30508, 30509, 30512, 30514, 30515, 30516,
        30521, 30522, 30523, 30526, 30530, 31498, 31499, 31500, 31501,
        31502, 31503, 31504, 31510, 31517, 31518, 31519, 31520, 31521,
        31522, 31524, 31525, 31530, 31531, 31533, 31535, 31537, 31539,
        31540, 31541, 31543, 31545, 31546, 31549, 32503, 32504, 32505,
        32506, 32508, 40224, 40226, 40227, 40229, 40230, 40231, 40232,
        40234, 40370, 40371, 40372, 40378, 40379, 40380, 40381, 40382,
        40383, 40390, 40391, 40400, 40401, 40402, 40403, 40406, 40407,
        40408, 40409, 40411, 40412, 40817, 40818, 40819, 40821, 40824,
        40828, 40829, 40830, 49689, 49690, 49691, 49697]),
 'AA Chavan': array([69456, 69457, 69458, 75227, 75231, 82373, 82374, 82375, 82377,
        82379, 82381]),
 'AA Jhunjhunwala': array([41371, 41372, 41373, 41376, 41377, 41380, 41383, 41384, 41385,
        41393, 41395, 42246, 42247, 42248, 42251, 42252, 42253, 42254,
        42255, 42256, 42257, 42259, 42260, 42261, 42264, 42265, 42269,
        42271, 42272, 42277, 42278, 42283, 42284, 42288, 42292, 42297,
        42298, 42299, 42300, 42301, 42302, 42304, 42305, 42308, 42309,
        42310, 42312, 42316, 42317, 42318, 42319, 42320, 42324, 42325,
        42326, 42328, 42329, 42330, 42332, 43199, 43201, 43202, 43204,
        43205, 43206, 43207, 43879, 43882, 43883, 43884, 43888, 43890,
        43893, 43895, 43896, 43897, 43898, 43899, 43900, 43902, 43905,
        43907, 43908, 43909, 43912, 43913, 43917, 43918, 43923, 43925,
        43926, 43927, 43930, 43931, 43932, 43936, 43937, 43938, 43940,
        43943, 43945, 43948, 43949, 46654, 46655, 46658, 46659, 46661,
        46664, 47901, 47903, 47904, 47914, 47919, 47920, 48731, 48732,
        48733, 48735, 49543, 49544, 49548, 49549, 49552, 49554, 49557,
        49560, 51797, 51798, 51801, 51802, 51806, 51808, 51811, 51812,
        51813, 51817, 51821, 51822, 51823, 51824, 51825, 51826, 51828,
        51829, 51832, 51833, 51837, 51839, 51842, 52635, 52636, 52637,
        52638, 52639, 52641, 52642, 52643, 52652, 52657, 52659, 52660,
        52661, 52662, 52663, 52664, 52665, 52669, 52670, 52676, 52678,
        52682, 65593, 65594, 65597, 65598, 65599, 65600, 65601, 65602,
        65603, 65612, 65613, 65614, 65618, 65619, 65623, 65624, 67300,
        67301, 67302, 76073, 76074, 76075, 76076, 76078, 76079, 83214,
        84865, 84866, 84867, 84868, 84869, 84871, 84872, 84874, 84876,
        84878, 84880, 84884, 84886, 84887, 84888, 84889, 84892, 84894,
        84898, 84901]),
 'AA Noffke': array([14040, 14041, 14042, 14043, 14046, 14051, 14052, 14053, 14054,
        14055, 14056, 14059]),
 'AB Agarkar': array([ 16559,  16560,  16562,  16567,  16570,  16573,  16574,  16575,
         16576,  17480,  17481,  17482,  17485,  17489,  17491,  17492,
         18262,  18263,  18264,  18266,  18267,  18268,  18269,  18270,
         18271,  18272,  18273,  18274,  18275,  18276,  18282,  19097,
         19100,  23096,  23097,  23098,  23099,  23100,  23101,  23102,
         23103,  23106,  23110,  23115,  23120,  23122,  23123,  24320,
         24321,  28018,  28022,  28023,  29274,  31098,  31100,  31104,
         31105,  31106,  31107,  31109,  31111,  35906,  35907,  35908,
         35909,  35911,  35916,  35920,  35921,  35922,  35924,  35925,
         35931,  35932,  35933,  35934,  35935,  35937,  35939,  35940,
         35941,  35943,  35946,  35947,  35949,  35950,  35951,  35955,
         35956,  35959,  39455,  39456,  39461,  39463,  39466,  39467,
         39468,  39472,  39473,  39480,  39483,  39486,  39487,  39489,
         39497,  39500,  39501,  47251,  47253,  47255,  47256,  47257,
         47258,  47260,  47264,  47266,  47270,  47271,  47272,  47273,
         48123,  48125,  48126,  48129,  48130,  51291,  51292,  51293,

### **ngroups**
Returns the total number of groups.

In [15]:
grouped.ngroups

3

In [16]:
# similarly
len(grouped)

3

# **Summary**
| Attribute | Return Type | What It Returns                                 | Example Output                                  |
| --------- | ----------- | ----------------------------------------------- | ----------------------------------------------- |
| `groups`  | `dict`      | Group names mapped to **index labels**          | `{'IT': Index([0, 2, 5]), 'HR': Index([1, 3])}` |
| `indices` | `dict`      | Group names mapped to **integer row positions** | `{'IT': array([0, 2, 5]), 'HR': array([1, 3])}` |
| `ngroups` | `int`       | Number of groups                                | `3`                                             |

<br>

# **Groupby Methods**

### **size()**
Returns the number of rows in each group.

It counts every row, including rows containing NaN.

**syntax:**

grouped.size()

In [17]:
grouped.size()

Department
HR       2
IT       3
Sales    1
dtype: int64

In [18]:
# similary

df["Department"].value_counts()

Department
IT       3
HR       2
Sales    1
Name: count, dtype: int64

### **get_group()**

get_group() returns one complete group from the GroupBy object.

Instead of returning all groups, it returns only the group you ask for.

**syntax:**

grouped.get_group(name)

In [19]:
grouped.get_group('HR')

    Name Department  Salary
1   Sara         HR   60000
3  Bilal         HR   65000

In [20]:
grouped.get_group("Sales")

     Name Department  Salary
4  Hassan      Sales   45000

In [21]:
grouped.get_group("IT")

     Name Department  Salary
0     Ali         IT   50000
2   Ahmed         IT   70000
5  Ayesha         IT   55000

### **first()**

Returns the first non-null row/value from each group.

If the first row has `NaN` in one column, Pandas may use the next non-null value for that specific column.

**syntax:**

grouped.first()

In [22]:
grouped.first()

              Name  Salary
Department
HR            Sara   60000
IT             Ali   50000
Sales       Hassan   45000

### **last()**

Exactly opposite of first().

Returns the last non-null row/value from every group.

**syntax:**

grouped.last()

In [23]:
grouped.last()

              Name  Salary
Department
HR           Bilal   65000
IT          Ayesha   55000
Sales       Hassan   45000

### **sample()**

It return any random rows from each group

**syntax:**

grouped.sample()

In [24]:
grouped.sample()

     Name Department  Salary
1    Sara         HR   60000
5  Ayesha         IT   55000
4  Hassan      Sales   45000

In [25]:
grouped.sample(2, replace=True)

     Name Department  Salary
3   Bilal         HR   65000
3   Bilal         HR   65000
0     Ali         IT   50000
5  Ayesha         IT   55000
4  Hassan      Sales   45000
4  Hassan      Sales   45000

### **nth()**

This is more flexible than first() and last().

Returns the nth row from every group.

**syntax:**

grouped.nth(n)

| Parameter | Default  | Accepted Values                | Purpose                                    | Explanation                                                                 |
| --------- | -------- | ------------------------------ | ------------------------------------------ | --------------------------------------------------------------------------- |
| `n`       | Required | Integer (positive or negative) | Choose which row to return from each group | `0` = first row, `1` = second row, `-1` = last row, `-2` = second last row. |

In [26]:
grouped.nth(0)      # give the first as grouped.first()

     Name Department  Salary
0     Ali         IT   50000
1    Sara         HR   60000
4  Hassan      Sales   45000

In [27]:
# similary 
grouped.first()

              Name  Salary
Department
HR            Sara   60000
IT             Ali   50000
Sales       Hassan   45000

In [28]:
# but we can get any row number of each group

grouped.nth(2)          # it give only the IT because IT group only contain 3 rows

     Name Department  Salary
5  Ayesha         IT   55000

### **describe()**

Returns a complete statistical summary for every group.

**syntax:**

grouped.describe()

In [29]:
grouped.describe()

           Salary                                                         \
            count          mean           std      min      25%      50%
Department
HR            2.0  62500.000000   3535.533906  60000.0  61250.0  62500.0
IT            3.0  58333.333333  10408.329997  50000.0  52500.0  55000.0
Sales         1.0  45000.000000           NaN  45000.0  45000.0  45000.0


                75%      max
Department
HR          63750.0  65000.0
IT          62500.0  70000.0
Sales       45000.0  45000.0

### **nunique()**

Counts the number of unique values inside every group.

**syntax:**

grouped.nunique()

In [30]:
grouped.nunique()

            Name  Salary
Department
HR             2       2
IT             3       3
Sales          1       1

### **agg()**

The agg() method (short for aggregate) applies one or more aggregation functions to a Series, DataFrame, or GroupBy object and combines the results into a single output.

**syntax:**

grouped.agg(fun)

In [31]:
grouped.agg('min')

              Name  Salary
Department
HR           Bilal   60000
IT           Ahmed   50000
Sales       Hassan   45000

In [32]:
grouped.agg('max')

              Name  Salary
Department
HR            Sara   65000
IT          Ayesha   70000
Sales       Hassan   45000

In [33]:
# on single colunns
grouped["Salary"].mean()

Department
HR       62500.000000
IT       58333.333333
Sales    45000.000000
Name: Salary, dtype: float64

In [34]:
# multiple operation
grouped.agg(['min', 'max'])

              Name         Salary
               min     max    min    max
Department
HR           Bilal    Sara  60000  65000
IT           Ahmed  Ayesha  50000  70000
Sales       Hassan  Hassan  45000  45000

In [35]:
grouped["Salary"].agg(["min", "max"])

              min    max
Department
HR          60000  65000
IT          50000  70000
Sales       45000  45000

In [36]:
# specific operation on specific columns
grouped.agg(
    {
        "Salary":'mean',
            "Name":'min'
    }
)

                  Salary    Name
Department
HR          62500.000000   Bilal
IT          58333.333333   Ahmed
Sales       45000.000000  Hassan

In [37]:
grouped.agg({
    "Salary":["min", "max", "mean"],
    "Name":["min", "max"]
})          
# actually this is a multiindex dataframe

           Salary                         Name
              min    max          mean     min     max
Department
HR          60000  65000  62500.000000   Bilal    Sara
IT          50000  70000  58333.333333   Ahmed  Ayesha
Sales       45000  45000  45000.000000  Hassan  Hassan

In [38]:
# giving name to each colunmn 

grouped.agg(
    salary_min=('Salary', "min"),
    salary_max=('Salary', "max")
)
# this is not a multiindex dataframe its a simple dataframe

            salary_min  salary_max
Department
HR               60000       65000
IT               50000       70000
Sales            45000       45000

### **apply()**
GroupBy.apply() applies a user-defined function (or a built-in function) to each group independently, then combines the results into one final object.

In one sentence:

Split the data → Send each group to your function → Collect every result → Return one combined object.

This is why it is called apply.

In [39]:
# it will return the min of salary of each group 
def mini(group):
    return group["Salary"].min()

grouped.apply(mini)       # in this way we can make any custom function and apply on the grouped object

Department
HR       60000
IT       50000
Sales    45000
dtype: int64

In [40]:
def maxi(group):
    return {
        "Salary_max":group["Salary"].max(),
        "Salary_min":group["Salary"].min()
    }
    
grouped.apply(maxi)

Department
HR       {'Salary_max': 65000, 'Salary_min': 60000}
IT       {'Salary_max': 70000, 'Salary_min': 50000}
Sales    {'Salary_max': 45000, 'Salary_min': 45000}
dtype: object

In [41]:
def statistics(group):

    return pd.Series({

        "Average":group["Salary"].mean(),

        "Max":group["Salary"].max(),

        "Min":group["Salary"].min()

    })

grouped.apply(statistics)

                 Average      Max      Min
Department
HR          62500.000000  65000.0  60000.0
IT          58333.333333  70000.0  50000.0
Sales       45000.000000  45000.0  45000.0

In [42]:
grouped.apply(lambda x: x.nlargest(1, 'Salary'))

                Name  Salary
Department
HR         3   Bilal   65000
IT         2   Ahmed   70000
Sales      4  Hassan   45000

# **Groupby with multiple columns**

In [43]:
movies.groupby(["Released_Year", "Genre"])["Gross"].sum().sort_values(ascending=False)

Released_Year  Genre
1962           Drama        3.683500e+09
2018           Action       2.936539e+09
1957           Drama        2.572110e+09
2008           Action       2.554671e+09
2009           Action       2.040015e+09
                                ...
1925           Drama        5.097000e+04
1931           Crime        2.887700e+04
1967           Drama        2.633100e+04
1928           Biography    2.187700e+04
1931           Comedy       1.918100e+04
Name: Gross, Length: 434, dtype: float64

# **Looping through groupby object**

We can iterate through groupby object and it give a tuple with two values the first is the name of group and second is dataframe or series.

In [44]:
for name,data in grouped:
    print(type(name))
    print(type(data))

<class 'str'>
<class 'pandas.DataFrame'>
<class 'str'>
<class 'pandas.DataFrame'>
<class 'str'>
<class 'pandas.DataFrame'>

In [45]:
for name,data in grouped:
    print(name.center(30))
    print(data)
    print("-"*30)

              HR
    Name Department  Salary
1   Sara         HR   60000
3  Bilal         HR   65000
------------------------------
              IT
     Name Department  Salary
0     Ali         IT   50000
2   Ahmed         IT   70000
5  Ayesha         IT   55000
------------------------------
            Sales
     Name Department  Salary
4  Hassan      Sales   45000
------------------------------

# **Some Question with Groupby**

### **find number of movies starting with A for each group**

In [46]:

grouped = movies.groupby("Genre")

grouped.apply(lambda x: x[x["Series_Title"].str.startswith("A")])

                      Series_Title Released_Year  Runtime  IMDB_Rating  \
Genre
Action 59        Avengers: Endgame          2019      181          8.4
       60   Avengers: Infinity War          2018      149          8.4
       106                  Aliens          1986      137          8.3
       166         Andaz Apna Apna          1994      160          8.2
       224             A Wednesday          2008      104          8.1
...                            ...           ...      ...          ...
Drama  804           Abre los ojos          1997      119          7.7
       813       A Little Princess          1995       97          7.7
       824          A Few Good Men          1992      138          7.7
       903          A Star Is Born          2018      136          7.6
Horror 75                    Alien          1979      117          8.4

                      Director             Star1  No_of_Votes        Gross  \
Genre
Action 59        Anthony Russo         Joe Russo       809955  858373000.0
       60        Anthony Russo         Joe Russo       834477  678815482.0
       106       James Cameron  Sigourney Weaver       652719   85160248.0
       166   Rajkumar Santoshi        Aamir Khan        49300  213351844.0
       224       Neeraj Pandey       Anupam Kher        73891  573329738.0
...                        ...               ...          ...          ...
Drama  804  Alejandro Amenábar   Eduardo Noriega        64082     368234.0
       813      Alfonso Cuarón   Liesel Matthews        32236   10019307.0
       824          Rob Reiner        Tom Cruise       235388  141340178.0
       903      Bradley Cooper         Lady Gaga       334312  215288866.0
Horror 75         Ridley Scott  Sigourney Weaver       787806   78900000.0

            Metascore
Genre
Action 59        78.0
       60        68.0
       106       84.0
       166        NaN
       224        NaN
...               ...
Drama  804        NaN
       813       83.0
       824       62.0
       903       88.0
Horror 75        89.0

[63 rows x 9 columns]

### **find ranking of each movie in the group according to IMDB score**

In [47]:
def ran(group):
    group["Rank"] = group["IMDB_Rating"].rank(ascending=False)
    return group

In [48]:
grouped.apply(ran)

                                                   Series_Title Released_Year  \
Genre
Action   2                                      The Dark Knight          2008
         5        The Lord of the Rings: The Return of the King          2003
         8                                            Inception          2010
         10   The Lord of the Rings: The Fellowship of the Ring          2001
         13               The Lord of the Rings: The Two Towers          2002
...                                                         ...           ...
Thriller 700                                    Wait Until Dark          1967
Western  12                     Il buono, il brutto, il cattivo          1966
         48                        Once Upon a Time in the West          1968
         115                         Per qualche dollaro in più          1965
         691                             The Outlaw Josey Wales          1976

              Runtime  IMDB_Rating           Director              Star1  \
Genre
Action   2        152          9.0  Christopher Nolan     Christian Bale
         5        201          8.9      Peter Jackson        Elijah Wood
         8        148          8.8  Christopher Nolan  Leonardo DiCaprio
         10       178          8.8      Peter Jackson        Elijah Wood
         13       179          8.7      Peter Jackson        Elijah Wood
...               ...          ...                ...                ...
Thriller 700      108          7.8      Terence Young     Audrey Hepburn
Western  12       161          8.8       Sergio Leone     Clint Eastwood
         48       165          8.5       Sergio Leone        Henry Fonda
         115      132          8.3       Sergio Leone     Clint Eastwood
         691      135          7.8     Clint Eastwood     Clint Eastwood

              No_of_Votes        Gross  Metascore  Rank
Genre
Action   2        2303232  534858444.0       84.0   1.0
         5        1642758  377845905.0       94.0   2.0
         8        2067042  292576195.0       74.0   3.5
         10       1661481  315544750.0       92.0   3.5
         13       1485555  342551365.0       87.0   6.0
...                   ...          ...        ...   ...
Thriller 700        27733   17550741.0       81.0   1.0
Western  12        688390    6100000.0       90.0   1.0
         48        302844    5321508.0       80.0   2.0
         115       232772   15000000.0       74.0   3.0
         691        65659   31800000.0       69.0   4.0

[1000 rows x 10 columns]

### **find normalized IMDB rating group wise**

In [49]:
def normal(group):
  group['norm_rating'] = (group['IMDB_Rating'] - group['IMDB_Rating'].min())/(group['IMDB_Rating'].max() - group['IMDB_Rating'].min())
  return group

In [50]:
grouped.apply(normal).reset_index(level=0)

,Genre,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore,norm_rating
2,Action,The Dark Knight,2008,152,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0,1.000000
5,Action,The Lord of the Rings: The Return of the King,2003,201,8.9,Peter Jackson,Elijah Wood,1642758,377845905.0,94.0,0.928571
8,Action,Inception,2010,148,8.8,Christopher Nolan,Leonardo DiCaprio,2067042,292576195.0,74.0,0.857143
10,Action,The Lord of the Rings: The Fellowship of the Ring,2001,178,8.8,Peter Jackson,Elijah Wood,1661481,315544750.0,92.0,0.857143
13,Action,The Lord of the Rings: The Two Towers,2002,179,8.7,Peter Jackson,Elijah Wood,1485555,342551365.0,87.0,0.785714
...,...,...,...,...,...,...,...,...,...,...,...
700,Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0,NaN
12,Western,"Il buono, il brutto, il cattivo",1966,161,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0,1.000000
48,Western,Once Upon a Time in the West,1968,165,8.5,Sergio Leone,Henry Fonda,302844,5321508.0,80.0,0.700000
115,Western,Per qualche dollaro in più,1965,132,8.3,Sergio Leone,Clint Eastwood,232772,15000000.0,74.0,0.500000
691,Western,The Outlaw Josey Wales,1976,135,7.8,Clint Eastwood,Clint Eastwood,65659,31800000.0,69.0,0.000000

### **find the most earning actor->director combo**

In [51]:
movies.groupby(["Director", "Star1"])["Gross"].sum().sort_values(ascending=False).head(1)

Director        Star1
Akira Kurosawa  Toshirô Mifune    2.999877e+09
Name: Gross, dtype: float64

### **find the best(in-terms of metascore(avg)) actor->genre combo**

In [55]:
group = movies.groupby(["Genre", "Star1"])["Metascore"].mean().reset_index().sort_values("Metascore", ascending=False)
group.nlargest(1, "Metascore", keep="all")

         Genre            Star1  Metascore
819    Mystery    James Stewart      100.0
593      Drama       Cary Grant      100.0
653      Drama  Humphrey Bogart      100.0
732      Drama     Orson Welles      100.0
620      Drama   Ellar Coltrane      100.0
163  Adventure    Peter O'Toole      100.0
575      Drama      Bertil Guve      100.0

### **find the top 10 batsman in terms of runs**

In [59]:
ipl.groupby("batsman")["batsman_runs"].sum().sort_values(ascending=False).head(10)

batsman
V Kohli           5434
SK Raina          5415
RG Sharma         4914
DA Warner         4741
S Dhawan          4632
CH Gayle          4560
MS Dhoni          4477
RV Uthappa        4446
AB de Villiers    4428
G Gambhir         4223
Name: batsman_runs, dtype: int64

### **find the batsman with max no of sixes**

In [68]:
six = ipl[ipl["batsman_runs"]==6]

six.groupby("batsman")["batsman"].count().sort_values(ascending=False).head(1).index[0]

'CH Gayle'

### **find batsman with most number of 4's and 6's in last 5 overs**

In [74]:
last_over = ipl[ipl["over"]>15]
last_over[last_over["batsman_runs"].isin([6, 4])].groupby("batsman")["batsman_runs"].sum().sort_values(ascending=False).head(1).index[0]

'MS Dhoni'

### **find V Kohli's record against all teams**

In [80]:
ipl[ipl["batsman"]=='V Kohli'].groupby('bowling_team')["batsman_runs"].sum().sort_values(ascending=False).reset_index()

               bowling_team  batsman_runs
0          Delhi Daredevils           763
1       Chennai Super Kings           749
2     Kolkata Knight Riders           675
3           Kings XI Punjab           636
4            Mumbai Indians           628
5       Sunrisers Hyderabad           509
6          Rajasthan Royals           370
7           Deccan Chargers           306
8             Gujarat Lions           283
9   Rising Pune Supergiants           188
10            Pune Warriors           128
11   Rising Pune Supergiant            83
12           Delhi Capitals            66
13     Kochi Tuskers Kerala            50

### **Create a function that can return the highest score of any batsmane**

In [138]:
batsman = ipl[ipl['batsman']=='V Kohli']
str(batsman.groupby("match_id")["batsman_runs"].sum().sort_values(ascending=False).head(1).values[0])

'113'