## **Questions based on Titanic Dataset:**

To read the dataset as csv, use the below code:

```python
import pandas as pd

url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv"
titanic_df = pd.read_csv(url)
```

In [1]:
import numpy as np
import pandas as pd

C:\Users\HP\AppData\Roaming\Python\Python313\site-packages\pandas\core\computation\expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

### `Q-1:` Using `groupby` make groups using the `"Pclass"` column and find out the average age and total number of missing values in the `"Age"` column for every group.

In [2]:
# code here
titanic = pd.read_csv('data/19_data/test - test.csv')


titanic.groupby("Pclass")["Age"].mean()

Pclass
1    40.918367
2    28.777500
3    24.027945
Name: Age, dtype: float64

In [3]:
titanic.groupby("Pclass").apply(lambda x:x["Age"].isna().sum())

Pclass
1     9
2     5
3    72
dtype: int64

### `Q-2:` Using `groupby` make groups using the `"Pclass"` column and fill every group's `"Embarked"` column's missing values with the mode value of that group. After that, print every group's `"Embarked"` column's value counts in ascending order.

In [4]:
# code here

grouped = titanic.groupby("Pclass")["Embarked"].transform(lambda x:x.fillna(x.mode().iloc[0]))

grouped = titanic.groupby("Pclass")["Embarked"]

for name, data in grouped:
    print(name)
    print(data.value_counts().sort_values())
    print("*"*30)

1
Embarked
Q     1
S    50
C    56
Name: count, dtype: int64
******************************
2
Embarked
Q     4
C    11
S    78
Name: count, dtype: int64
******************************
3
Embarked
C     35
Q     41
S    142
Name: count, dtype: int64
******************************

### `Q-3:` Make groups based on `"Embarked"` column. And for each of this embarked group, make another group based on `"Pclass"` and find out the average fare (round off up to 2 decimal places) for each "Pclass" for each group of "Embarked".

**Sample Output:**

```bash
{'C': {1: 105, 2: 25, 3: 11},
 'Q': {1: 90, 2: 12, 3: 11},
 'S': {1: 70, 2: 20, 3: 15}}
```

In [5]:
# code here

group1 = titanic.groupby("Embarked")
dic = {}
for name, data in group1:
    avg = round(data.groupby("Pclass")['Fare'].mean(), 2)
    dic[name]=dict(avg)
    
dic

{'C': {1: np.float64(110.07), 2: np.float64(20.12), 3: np.float64(10.66)},
 'Q': {1: np.float64(90.0), 2: np.float64(11.27), 3: np.float64(9.0)},
 'S': {1: np.float64(76.68), 2: np.float64(23.06), 3: np.float64(13.91)}}

## **Questions Based on Fifa Worldcup - 2022 Dataset:**

You can read the dataset by using the below sample code

```python
import pandas as pd

fifa_df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv")
```

### `Q-4:` Perform `groupby` based on the `"Team"` column and then perform Z Normalization on top of the below columns of each group:
1. Passes
2. Passes Completed
3. Attempted Line Breaks
4. Completed Line Breaks

You have to make a python function named `z_normalization` which takes two arguments:

1. *group:* Every group that you have created
2. *cols_to_perform:* This parameter takes a list of columns on which you have to perform the Z-Normalization.

For this problem, you have to use th `apply()` method.

$\Large Z \ - \ Normalization = \frac{X_i - \mu}{std} $

In [6]:
# code here
pd.options.display.max_columns = None
fifa = pd.read_csv("data/19_data/Fifa Worldcup 2022.csv")
grouped = fifa.groupby("Team")

def z_normalize(group, li):
    for i in li:
        group[i] = (group[i]-group[i].mean())/np.std(group[i])
    return group

l = ["Passes", "Passes Completed", "Attempted Line Breaks", "Completed Line Breaks"]


grouped.apply(z_normalize, l)

               Sl. No  Match No.        Against Group  Goal  Possession (%)  \
Team
Argentina 8         9          5   Saudi Arabia     C     1              51
          46       47         24         Mexico     C     2              50
          77       78         39         Poland     C     2              67
          98       99         50      Australia     C     2              53
          115     116         58    Netherlands     C     2              44
...               ...        ...            ...   ...   ...             ...
Uruguay   63       64         32       Portugal     H     0              35
          89       90         45          Ghana     H     2              39
Wales     7         8          4  United States     B     1              39
          32       33         17           Iran     B     0              51
          68       69         35        England     B     0              33

               Inside Penalty Area  Outside Penalty Area  Assists  \
Team
Argentina 8                      1                     0        0
          46                     1                     1        2
          77                     1                     1        2
          98                     2                     0        1
          115                    2                     0        1
...                            ...                   ...      ...
Uruguay   63                     0                     0        0
          89                     2                     0        1
Wales     7                      1                     0        0
          32                     0                     0        0
          68                     0                     0        0

               Total Attempts  On Target  Off Target  Target in Penalty  \
Team
Argentina 8                14          6           6                 10
          46                5          2           3                  2
          77               25         13           8                 10
          98               14          5           7                 11
          115              15          6           8                  5
...                       ...        ...         ...                ...
Uruguay   63               10          3           6                  6
          89               12          7           5                  7
Wales     7                 7          3           3                  5
          32               10          3           4                  5
          68                7          1           3                  1

               Target from Outside  Left Channel  Left Inside Channel  \
Team
Argentina 8                      4            12                    4
          46                     3            10                    6
          77                    15            25                    8
          98                     3            15                    6
          115                   10             7                    7
...                            ...           ...                  ...
Uruguay   63                     4            13                    8
          89                     5             7                    2
Wales     7                      2             7                    2
          32                     5            18                    3
          68                     6             7                    1

               Central Channel  Right Inside Channel  Right Channel  \
Team
Argentina 8                  5                     8             18
          46                 2                     4             12
          77                 7                    10             26
          98                11                     2             17
          115               13                     6             17
...                        ...                   ...            ...
Uruguay   63                 4                     5              9
          89                13                     3             17
Wales     7                  5                     2              7
          32                 8                    11             13
          68                 2                     0              4

               Receptions MD  Receptions D  Attempted Line Breaks  \
Team
Argentina 8               91            27               0.393969
          46              89             2              -0.859569
          77             150            36              -1.110277
          98             127             8               0.003979
          115            104             7               0.616820
...                      ...           ...                    ...
Uruguay   63              94             6              -0.592999
          89             186            14               1.408374
Wales     7               73             9               0.277153
          32             101            13               1.062419
          68              46             1              -1.339572

               Completed Line Breaks  Attempted Defensive Line Breaks  \
Team
Argentina 8                 0.094406                               10
          46               -1.020760                               10
          77                0.053103                               20
          98                0.424825                               16
          115              -0.112107                               24
...                              ...                              ...
Uruguay   63               -0.763604                               17
          89                1.412667                               24
Wales     7                 0.239244                               17
          32                1.087471                               17
          68               -1.326714                                4

               Completed Defensive Line Breaks  Yellow Cards  Red Cards  \
Team
Argentina 8                                  8             0          0
          46                                 5             1          0
          77                                16             1          0
          98                                 8             0          0
          115                                8             8          0
...                                        ...           ...        ...
Uruguay   63                                11             2          0
          89                                14             3          0
Wales     7                                  8             2          0
          32                                 8             1          1
          68                                 1             2          0

               Fouls Against  Offsides    Passes  Passes Completed  Crosses  \
Team
Argentina 8                7        10 -0.224815         -0.170538       36
          46              15         2 -0.680960         -0.620043       14
          77              11         0  1.820239          1.959082       22
          98               8         4  0.672272          0.640044        6
          115             18         2 -0.148790         -0.273703       16
...                      ...       ...       ...               ...      ...
Uruguay   63              16         0 -1.141098         -1.095678       18
          89              11         2 -0.152931         -0.226510       15
Wales     7               10         1 -0.066851         -0.170638       15
          32               9         2  1.256801          1.301116       20
          68              16         1 -1.189950         -1.130478        4

               Crosses Completed  Corners  Free Kicks  Penalties Scored  Pts
Team
Argentina 8                   15        9          21                 1    0
          46                   2        4          23                 0    3
          77                   5        9           5                 0    3
          98                   1        1          15                 0    3
          115                  4        8          30                 5    3
...                          ...      ...         ...               ...  ...
Uruguay   63                   5        2          13                 0    0
          89                   4        2          20                 0    3
Wales     7                    6        3          15                 1    1
          32                   5        2          12                 0    1
          68                   1        1          10                 0    0

[128 rows x 37 columns]

## **Questions on IPL wala dataset**

ball by ball dataset - https://drive.google.com/file/d/1-kvv_9KCSAFWcrhS9WgTxSrURkRh6GNt/view?usp=share_link

### `Q-5:` Find batsman in below category-
* Highest score while chasing
* Best Strike rate while chasing and have faced 100+ balls


> Chasing mean team batting in second inning

In [7]:
# code here
ipl = pd.read_csv('data/19_data/deliveries.csv')
fil = ipl[ipl["inning"]==2]
fil.groupby(["match_id", "batsman"])["batsman_runs"].sum().sort_values(ascending=False)
st = fil.groupby(["match_id", "batsman"])["batsman_runs"].agg(['sum', 'count'])
st = st.reset_index()
st.rename(columns={
    "sum":'runs', 
    "count":"ball"
}, inplace=True)
st_100 = st[st["ball"]>100]
st_100["rate"] = (st_100["runs"]/st_100["ball"])*100
st_100.sort_values(by="rate", ascending=False)

Empty DataFrame
Columns: [match_id, batsman, runs, ball, rate]
Index: []

### `Q-6` Most Successful bowler against any batsman. Find that pair of bowler and batsman.
> Most Successful in terms of dissmissal. A bowler who have dissmissed any batsman most no of times. If any two pairs have same no of dissmisal, consider runs conceded by bowler to that batsman. Those who have concede lesser runs is more successful.

In [8]:
# code here

ipl.groupby(["batsman", "bowler"])[["batsman_runs", "player_dismissed"]].agg({"batsman_runs":'sum',"player_dismissed":'count'}).sort_values(by=["player_dismissed", "batsman_runs"], ascending=[False, True])

                          batsman_runs  player_dismissed
batsman    bowler
PA Patel   B Kumar                  66                 7
MS Dhoni   Z Khan                   74                 7
           PP Ojha                  98                 7
RG Sharma  R Vinay Kumar            22                 6
           SK Trivedi               45                 6
...                                ...               ...
JA Morkel  SK Warne                 89                 0
JH Kallis  Z Khan                   92                 0
SR Watson  M Kartik                 94                 0
KD Karthik JD Unadkat              105                 0
V Kohli    R Ashwin                153                 0

[19821 rows x 2 columns]

### `Q-7`: Most successful batting pair in IPL. Batting pair who have scored most runs playing together.

In [14]:
ipl["Pair"] = ((ipl["batsman"]+","+ipl["non_striker"]).str.split(",")).apply(lambda x:sorted(x)).str.join(",").str.replace(",", " - ")
ipl.groupby("Pair")["total_runs"].sum().sort_values(ascending=False).head(1)

Pair
AB de Villiers - V Kohli    2860
Name: total_runs, dtype: int64

### `Q-8:` Make a dataframe for all batting pairs played together.
```
Batsman1 Batsman2 Runs Avg StrikeRate
```

> Just to ease this question you can count wide-balls for strike rate.

In [54]:
# code here


ipl[["batsman1", 'batsman2']] = ipl["Pair"].str.split(" - ", expand=True)
fil = ipl.groupby(["batsman1", "batsman2"])[["wide_runs", "batsman_runs"]].sum().reset_index()
fil["total_runs"] = fil["wide_runs"] + fil["batsman_runs"]
fil.drop(columns=["wide_runs", "batsman_runs"], inplace=True)

In [55]:
dff = ipl.groupby(["batsman1", "batsman2"])["batsman_runs"].count().sort_values(ascending=False).reset_index()

In [62]:
dff.rename(columns={
    "batsman_runs":"balls"
}, inplace=True)

In [69]:
final = pd.merge(fil, dff, on=["batsman1", "batsman2"], how='inner')
final["strike_rate"] = round((final["total_runs"]/final["balls"])*100, 2)

In [70]:
final

            batsman1         batsman2  total_runs  balls  strike_rate
0     A Ashish Reddy         A Mishra          40     31       129.03
1     A Ashish Reddy  AA Jhunjhunwala           4      5        80.00
2     A Ashish Reddy         CL White          13      9       144.44
3     A Ashish Reddy     DB Ravi Teja          10      7       142.86
4     A Ashish Reddy        DJG Sammy          45     34       132.35
...              ...              ...         ...    ...          ...
3425      WD Parnell     Yuvraj Singh          41     18       227.78
3426         WP Saha        YK Pathan          17      9       188.89
3427      WPUJC Vaas  Y Venugopal Rao          42     26       161.54
3428         Y Nagar  Y Venugopal Rao         143    138       103.62
3429     YV Takawale     Yuvraj Singh           1      3        33.33

[3430 rows x 5 columns]