## Sleep Efficiency Dataset
For questions 1-5, you can find the dataset and details about it from [here](https://www.kaggle.com/datasets/equilibriumm/sleep-efficiency).

`ID`
a unique identifier for each test subject

`Age`
age of the test subject

`Gender`
male or female

`Bedtime`
the time the test subject goes to bed each night

`Wakeup time`
the time the test subject wakes up each morning

`Sleep duration`
the total amount of time the test subject slept (in hours)

`Sleep efficiency`
a measure of the proportion of time in bed spent asleep

`REM sleep percentage`
the percentage of total sleep time spent in REM sleep

`Deep sleep percentage`
the percentage of total sleep time spent in deep sleep

`Light sleep percentage`
the percentage of total sleep time spent in light sleep

`Awakenings`
the number of times the test subject wakes up during the night

`Caffeine consumption`
the amount of caffeine consumed in the 24 hours prior to bedtime (in mg)

`Alcohol consumption`
the amount of alcohol consumed in the 24 hours prior to bedtime (in oz)

`Smoking status`
whether or not the test subject smokes

`Exercise frequency`
the number of times the test subject exercises each week

### export the dataset to database

In [2]:
import pandas as pd
from sqlalchemy import create_engine

In [ ]:
engine = create_engine("mysql+mysqldb://root:@localhost/import_practice")

In [ ]:
pd.read_csv("Sleep_Efficiency.csv").to_sql(name="sleep", con=engine, if_exists='append', index=False)

452

### connect the python to database to run query

In [5]:
import mysql.connector

con = mysql.connector.connect(
    user="root", 
    password='',
    host='localhost', 
    database='import_practice'
)

### **`Problem 1:`**

**The question is:**

Find out the average sleep duration of top 15 male candidates who's sleep duration are equal to 7.5 or greater than 7.5.

In [31]:
pd.read_sql_query("SELECT AVG(`Sleep duration`) FROM sleep WHERE `Sleep duration`>=7.5 AND Gender='Male' ORDER BY `Sleep duration` DESC LIMIT 15", con=con)

C:\Users\HP\AppData\Local\Temp\ipykernel_5652\3401430317.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT AVG(`Sleep duration`) FROM sleep WHERE `Sleep duration`>=7.5 AND Gender='Male' ORDER BY `Sleep duration` DESC LIMIT 15", con=con)

   AVG(`Sleep duration`)
0               8.015873

### `Problem 2:` Show avg deep sleep time for both gender. Round result at 2 decimal places.

Note: sleep time and deep sleep percentage will give you, deep sleep time.

In [44]:
pd.read_sql_query("SELECT Gender, AVG(ROUND(`Sleep duration`*(`Deep sleep percentage`/100), 2)) AS deep_sleep_time FROM sleep GROUP BY Gender", con=con)

C:\Users\HP\AppData\Local\Temp\ipykernel_5652\270554371.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT Gender, AVG(ROUND(`Sleep duration`*(`Deep sleep percentage`/100), 2)) AS deep_sleep_time FROM sleep GROUP BY Gender", con=con)

   Gender  deep_sleep_time
0  Female         3.867411
1    Male         4.008246


### **`Problem 3:`**


**The question is:**

Find out the lowest 10th to 30th light sleep percentage records where deep sleep percentage values are between 25 to 45. Display age, light sleep percentage and deep sleep percentage columns only.

In [58]:
pd.read_sql_query("SELECT age, `light sleep percentage`, `deep sleep percentage` FROM sleep WHERE `deep sleep percentage`BETWEEN 25 AND 45 ORDER BY `light sleep percentage` ASC LIMIT 9, 20", con=con)

C:\Users\HP\AppData\Local\Temp\ipykernel_5652\2410618889.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT age, `light sleep percentage`, `deep sleep percentage` FROM sleep WHERE `deep sleep percentage`BETWEEN 25 AND 45 ORDER BY `light sleep percentage` ASC LIMIT 9, 20", con=con)

    age  light sleep percentage  deep sleep percentage
0    23                      45                     35
1    37                      45                     25
2    13                      45                     37
3    23                      45                     40
4    11                      45                     37
5    23                      45                     35
6    41                      45                     35
7    32                      45                     35
8    62                      45                     35
9    44                      45                     35
10   40                      45                     35
11   55                      45                     35
12   44                      46                     28
13   12                      47                     35
14   39                      47                     35
15   14                      47                     35
16   55                      47                     25
17   33                      47                     25
18   42                      47                     35
19   42                      47                     35



### `Problem 4:` Group by on exercise frequency and smoking status and show average deep sleep time, average light sleep time and avg rem sleep time.

* Note the differences in deep sleep time for smoking and non smoking status

In [67]:
pd.read_sql_query("SELECT `Exercise frequency`, `Smoking status`, AVG(`deep sleep percentage`), AVG(`light sleep percentage`), AVG(`REM sleep percentage`) FROM sleep GROUP BY `Exercise frequency`, `Smoking status`", con=con)

C:\Users\HP\AppData\Local\Temp\ipykernel_5652\1162366924.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT `Exercise frequency`, `Smoking status`, AVG(`deep sleep percentage`), AVG(`light sleep percentage`), AVG(`REM sleep percentage`) FROM sleep GROUP BY `Exercise frequency`, `Smoking status`", con=con)

,Exercise frequency,Smoking status,AVG(`deep sleep percentage`),AVG(`light sleep percentage`),AVG(`REM sleep percentage`)
0,NaN,No,66.7500,15.0000,18.2500
1,NaN,Yes,46.5000,32.0000,21.5000
2,0.0,No,49.7765,28.3647,21.8588
3,0.0,Yes,43.8710,34.2258,21.9032
4,1.0,No,54.0000,21.9286,24.0714
5,1.0,Yes,48.3902,27.8049,23.8049
6,2.0,No,61.1333,19.4333,19.4333
7,2.0,Yes,53.8750,22.9167,23.2083
8,3.0,No,57.1184,19.1184,23.7632
9,3.0,Yes,47.9259,29.5370,22.5370
10,4.0,No,60.1250,17.6750,22.2000
11,4.0,Yes,35.0000,45.0000,20.0000
12,5.0,No,57.0000,20.2857,22.7143
13,5.0,Yes,22.0000,63.0000,15.0000


### `Problem 5:` Group By on Awekning and show AVG Caffeine consumption, AVG Deep sleep time and AVG Alcohol consumption only for people who do exercise atleast 3 days a week. Show result in descending order awekenings

In [87]:
pd.read_sql_query("SELECT Awakenings, AVG(`Caffeine consumption`), AVG(`Alcohol consumption`), ROUND(AVG(`Sleep duration`*(`Deep sleep percentage`/100)), 2) FROM sleep WHERE `Exercise frequency`=3.0 GROUP BY `Awakenings` ORDER BY Awakenings DESC", con=con)

C:\Users\HP\AppData\Local\Temp\ipykernel_5652\2337611983.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT Awakenings, AVG(`Caffeine consumption`), AVG(`Alcohol consumption`), ROUND(AVG(`Sleep duration`*(`Deep sleep percentage`/100)), 2) FROM sleep WHERE `Exercise frequency`=3.0 GROUP BY `Awakenings` ORDER BY Awakenings DESC", con=con)

,Awakenings,AVG(`Caffeine consumption`),AVG(`Alcohol consumption`),"ROUND(AVG(`Sleep duration`*(`Deep sleep percentage`/100)), 2)"
0,4.0,7.812500,1.400000,3.57
1,3.0,3.125000,1.750000,3.47
2,2.0,8.928571,1.428571,3.67
3,1.0,10.000000,1.083333,4.22
4,0.0,29.807692,0.680000,4.44
5,NaN,21.875000,2.125000,4.01

### Export the data to database

In [88]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:@localhost/import_practice")

pd.read_csv("PowerGeneration.csv").to_sql(name="Power", con=engine, index=False)

C:\Users\HP\AppData\Local\Temp\ipykernel_5652\503113434.py:6: UserWarning: The provided table name 'Power' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  pd.read_csv("PowerGeneration.csv").to_sql(name="Power", con=engine, index=False)

334994

### Import data from database/make connection

In [89]:
import pandas as pd
import mysql.connector


con = mysql.connector.connect(
    user='root',
    password='',
    host='localhost',
    database='import_practice'
)

## Power Generation Dataset

For this question, you can find the details as well as the dataset from [here](https://www.kaggle.com/datasets/arvindnagaonkar/power-generation-data).

### **`Problem 6:`**



**The question is:**

Display those power stations which have average 'Monitored Cap.(MW)' (display the values) between 1000 and 2000 and the number of occurance of the power stations (also display these values) are
greater than 200. Also sort the result in ascending order.

In [99]:
pd.read_sql_query("SELECT `Power Station` AS 'station', COUNT(*) AS 'count', AVG(`Monitored Cap.(MW)`) AS 'avg_monitored' FROM Power GROUP BY `Power Station` HAVING avg_monitored BETWEEN 1000 AND 2000 AND count>200 ORDER BY avg_monitored ASC", con=con)

C:\Users\HP\AppData\Local\Temp\ipykernel_5652\2703676661.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT `Power Station` AS 'station', COUNT(*) AS 'count', AVG(`Monitored Cap.(MW)`) AS 'avg_monitored' FROM Power GROUP BY `Power Station` HAVING avg_monitored BETWEEN 1000 AND 2000 AND count>200 ORDER BY avg_monitored ASC", con=con)

                 station  count  avg_monitored
0                   NTPL   1863    1000.000000
1                   HNPC   1865    1040.000000
2                    MPL   1859    1050.000000
3              ESSARPMPL   1859    1071.221087
4             RWPL (JSW)   1413    1080.000000
5                  JSWBL    446    1080.000000
6                  JPPVL   3718    1110.000000
7                   CESC   1865    1125.000000
8      TOR. POW. (SUGEN)   1859    1147.500000
9                  NPGCL   1187    1177.657961
10                   SEL   1413    1179.193206
11                MBPMPL   1859    1200.000000
12                 RPSCL   1865    1200.000000
13                  EPGL   1859    1200.000000
14                 DBPCL   1864    1200.000000
15                  CEPL   1859    1200.000000
16                 JITPL   1859    1200.000000
17                 ITPCL   1859    1200.000000
18                Sikkim   1879    1200.000000
19                  UPCL   1865    1200.000000
20                 LAPPL   1859    1200.000000
21                     0   3080    1201.912792
22           Uttarakhand   1885    1265.837003
23     Jammu and Kashmir   1879    1285.000000
24                 HBPCL   1859    1312.442173
25              JhPL(HR)   1865    1320.000000
26                  SGPL    442    1320.000000
27                RKMPPL   1859    1333.491124
28                  STPL   1363    1358.914160
29                  GCEL   1864    1370.000000
30                  THDC   1865    1400.000000
31                   NPL   1859    1400.000000
32             KONDAPALI   1877    1452.886372
33                 APCPL   1865    1500.000000
34                 NTECL   1865    1500.000000
35                  NHDC   1863    1520.000000
36               NEEPCO.   1859    1685.975256
37                   NLC   3724    1694.629431
38           RATTANINDIA   1850    1711.216216
39      Himachal Pradesh   1885    1802.715650
40                  NHPC   5577    1805.350690
41                 SJVNL   1865    1912.020000
42  TOR. POW. (UNOSUGEN)   1865    1968.242627
43                  TSPL   1864    1980.000000
44        PPGCL (Jaypee)   1859    1980.000000
45                 LPGCL   1865    1980.000000
46                 RGPPL   1859    1989.528531