## Dataset
Data Link-> https://drive.google.com/drive/folders/1bGgNTDy5L_IodNcGHdB_SNCkUI5MUjmY?usp=share_link
Four Tables:
* Customer
* Employee
* Sales
* Products

In [91]:
import pandas as pd
import mysql.connector

con = mysql.connector.connect(
    host="localhost",
    user="root",
    password="",
    database="import_practice"
)

In [3]:
pd.read_sql_query("show tables", con=con)

C:\Users\HP\AppData\Local\Temp\ipykernel_11696\2939305109.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("show tables", con=con)

   Tables_in_import_practice
0                  customers
1                  employees
2                   inovices
3                  insurance
4                   invoices
5                 orderleads
6                      power
7                   products
8                     sales1
9                  salesteam
10                     sleep

### `Q-1` Find top-5 most sold products.

In [22]:
pd.read_sql_query("select t2.Name, SUM(t1.Quantity) AS Quantity from sales1 AS t1 INNER JOIN products AS t2 ON t1.ProductID=t2.ProductID GROUP BY Name ORDER BY Quantity DESC LIMIT 5", con=con)

C:\Users\HP\AppData\Local\Temp\ipykernel_11696\18531674.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("select t2.Name, SUM(t1.Quantity) AS Quantity from sales1 AS t1 INNER JOIN products AS t2 ON t1.ProductID=t2.ProductID GROUP BY Name ORDER BY Quantity DESC LIMIT 5", con=con)

                            Name  Quantity
0          Touring-3000 Blue, 54   38680.0
1                Rear Derailleur   34314.0
2  ML Mountain Frame - Black, 44   31080.0
3        Mountain-100 Silver, 38   28080.0
4            LL Road Seat/Saddle   27600.0

<br>



### `Q-2:` Find sales man who sold most no of products.

In [50]:
pd.read_sql_query("Select FirstName, LastName, SUM(Quantity) AS Quantity From employees INNER JOIN sales1 ON employees.EmployeeID=sales1.SalesPersonID GROUP BY FirstName, LastName ORDER BY Quantity DESC LIMIT 1", con=con)

C:\Users\HP\AppData\Local\Temp\ipykernel_11696\3168962623.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("Select FirstName, LastName, SUM(Quantity) AS Quantity From employees INNER JOIN sales1 ON employees.EmployeeID=sales1.SalesPersonID GROUP BY FirstName, LastName ORDER BY Quantity DESC LIMIT 1", con=con)

  FirstName LastName  Quantity
0   Abraham   Bennet  115410.0

### `Q-3:` Sales man name who has most no of unique customer.

In [83]:
pd.read_sql_query("Select employees.FirstName AS employee_first, employees.LastName AS employee_last, COUNT(DISTINCT sales1.CustomerID) From employees INNER JOIN sales1 ON employees.EmployeeID=sales1.SalesPersonID INNER JOIN customers ON sales1.CustomerID=customers.CustomerID GROUP BY employee_first, employee_last", con=con)

C:\Users\HP\AppData\Local\Temp\ipykernel_11696\3111294530.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("Select employees.FirstName AS employee_first, employees.LastName AS employee_last, COUNT(DISTINCT sales1.CustomerID) From employees INNER JOIN sales1 ON employees.EmployeeID=sales1.SalesPersonID INNER JOIN customers ON sales1.CustomerID=customers.CustomerID GROUP BY employee_first, employee_last", con=con)

  employee_first employee_last  COUNT(DISTINCT sales1.CustomerID)
0        Abraham        Bennet                                  1
1           Burt    Gringlesby                                  1
2       Charlene      Locksley                                  1
3          Innes  del Castillo                                  1
4          Livia        Karsen                                  1
5        Michael       O'Leary                                  1
6         Sheryl        Hunter                                  1
7        Stearns    MacFeather                                  1
8         Sylvia      Panteley                                  1


### `Q-4:` Sales man who has generated most revenue. Show top 5.

In [104]:
pd.read_sql_query("SELECT employees.FirstName, employees.LastName, SUM(sales1.Quantity*products.Price) AS revenue FROM sales1 INNER JOIN products ON sales1.ProductID=products.ProductID INNER JOIN employees ON sales1.SalesPersonID=employees.EmployeeID GROUP BY FirstName, LastName ORDER BY revenue DESC LIMIT 5", con=con)

C:\Users\HP\AppData\Local\Temp\ipykernel_11696\3669458690.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT employees.FirstName, employees.LastName, SUM(sales1.Quantity*products.Price) AS revenue FROM sales1 INNER JOIN products ON sales1.ProductID=products.ProductID INNER JOIN employees ON sales1.SalesPersonID=employees.EmployeeID GROUP BY FirstName, LastName ORDER BY revenue DESC LIMIT 5", con=con)

  FirstName  LastName       revenue
0      Dirk  Stringer  1.143393e+08
1    Michel  DeFrance  6.784428e+07
2    Albert    Ringer  4.915598e+07
3   Abraham    Bennet  3.999533e+07
4   Heather  McBadden  3.597071e+07


### `Q-5:` List all customers who have made more than 10 purchases.

In [ ]:
pd.read_sql_query("SELECT FirstName, LastName, COUNT(*) AS purchases FROM sales1 INNER JOIN customers ON sales1.SalesPersonID=customers.CustomerID GROUP BY FirstName, LastName HAVING COUNT(*)>10 ORDER BY purchases DESC", con=con)

C:\Users\HP\AppData\Local\Temp\ipykernel_11696\1690652391.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT FirstName, LastName, COUNT(*) AS purchases FROM sales1 INNER JOIN customers ON sales1.SalesPersonID=customers.CustomerID GROUP BY FirstName, LastName HAVING COUNT(*)>10 ORDER BY purchases DESC LIMIT 10", con=con)

  FirstName   LastName  purchases
0     Aaron  Alexander        226
1     Aaron        Jai        133
2     Aaron    Edwards        129
3     Aaron  Henderson        106
4     Aaron       Chen        104
5     Aaron     Foster        101
6     Aaron     Powell         99
7     Aaron        Con         97
8     Aaron   Gonzales         93
9     Aaron        Lal         91